/*
 * bindgen umbrella header: every public ocerz header, so the generated ffi
 * module sees the same declarations the C tree compiles against.
 */
#include "ocerz/a64emit.h"
#include "ocerz/abi.h"
#include "ocerz/apidb.h"
#include "ocerz/blocks.h"
#include "ocerz/bridge.h"
#include "ocerz/cache.h"
#include "ocerz/cpu.h"
#include "ocerz/decode.h"
#include "ocerz/dyld.h"
#include "ocerz/dyldapi.h"
#include "ocerz/flags.h"
#include "ocerz/flags_live.h"
#include "ocerz/interp.h"
#include "ocerz/interp_common.h"
#include "ocerz/jit.h"
#include "ocerz/leaf.h"
#include "ocerz/loader.h"
#include "ocerz/mem.h"
#include "ocerz/mode.h"
#include "ocerz/objcbridge.h"
#include "ocerz/sys_raw.h"
#include "ocerz/sysbridge.h"
#include "ocerz/syscall.h"
#include "ocerz/tcache.h"
#include "ocerz/types.h"
#include "ocerz/version.h"
#include "ocerz/vm.h"
#include "ocerz/x87.h"
