/*
 * Every SDK header that declares part of libSystem, for sdkgen to parse at once.
 *
 * libSystem has no umbrella header of its own, so this is one.  It is every
 * header under usr/include except four kinds.  The first is headers that
 * belong to some other library the SDK happens to ship - curses, zlib, sqlite,
 * libxml2, krb5, ICU, Tcl and the rest - because a declaration can only match an
 * export of the library being generated, and their macros would otherwise leak
 * into the headers after them.  The second is the i386 and arm machine
 * directories, which are reached through machine/, and nfs/, whose AUTH_*
 * macros break the Sun RPC headers that declare libSystem's xdr and clnt
 * functions.  The third is headers that do not compile on their own for both
 * x86_64 and arm64 even after the few includes at the top of the list:
 * dispatch/, xpc/ and os/workgroup subheaders that insist on their umbrella,
 * and ucontext.h, which requires _XOPEN_SOURCE.  The fourth is headers that
 * compile alone but not beside the rest: nlist.h and ranlib.h redefine the
 * structures of their mach-o/ namesakes, rpc/rpc.h, rpc/rpc_msg.h and the
 * rpcgen outputs under rpcsvc/ redefine one another, and two ndr_def.h copies
 * and net/if_var_status.h clash with what came before.
 *
 * tools/sdkgen/scan_headers.py wrote the list below by compiling every
 * candidate alone for both targets and then adding the survivors in sorted
 * order, dropping any that broke the growing set, and rewrites it the same way
 * for a new SDK.  sdkgen refuses to generate anything if this file produces an
 * error on either target, so a header that stops fitting is named rather than
 * silently lost.
 */
#include <sys/types.h>
#include <stdarg.h>
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/in_systm.h>
#include <mach/mach.h>
#include <AssertMacros.h>
#include <Availability.h>
#include <AvailabilityInternal.h>
#include <AvailabilityInternalLegacy.h>
#include <AvailabilityMacros.h>
#include <AvailabilityVersions.h>
#include <Block.h>
#include <CommonCrypto/CommonCrypto.h>
#include <CommonCrypto/CommonCryptoError.h>
#include <CommonCrypto/CommonCryptor.h>
#include <CommonCrypto/CommonDigest.h>
#include <CommonCrypto/CommonHMAC.h>
#include <CommonCrypto/CommonKeyDerivation.h>
#include <CommonCrypto/CommonRandom.h>
#include <CommonCrypto/CommonSymmetricKeywrap.h>
#include <ConditionalMacros.h>
#include <MacTypes.h>
#include <NSSystemDirectories.h>
#include <TargetConditionals.h>
#include <___wctype.h>
#include <__libunwind_config.h>
#include <__wctype.h>
#include <__xlocale.h>
#include <_abort.h>
#include <_assert.h>
#include <_bounds.h>
#include <_ctermid.h>
#include <_ctype.h>
#include <_inttypes.h>
#include <_langinfo.h>
#include <_locale.h>
#include <_locale_posix2008.h>
#include <_mb_cur_max.h>
#include <_monetary.h>
#include <_printf.h>
#include <_regex.h>
#include <_static_assert.h>
#include <_stdio.h>
#include <_stdlib.h>
#include <_string.h>
#include <_strings.h>
#include <_time.h>
#include <_types.h>
#include <_types/_intmax_t.h>
#include <_types/_locale_t.h>
#include <_types/_nl_item.h>
#include <_types/_uint16_t.h>
#include <_types/_uint32_t.h>
#include <_types/_uint64_t.h>
#include <_types/_uint8_t.h>
#include <_types/_uintmax_t.h>
#include <_types/_wctrans_t.h>
#include <_types/_wctype_t.h>
#include <_wchar.h>
#include <_wctype.h>
#include <_xlocale.h>
#include <aio.h>
#include <aliasdb.h>
#include <alloca.h>
#include <ar.h>
#include <arpa/ftp.h>
#include <arpa/inet.h>
#include <arpa/nameser.h>
#include <arpa/nameser_compat.h>
#include <arpa/telnet.h>
#include <arpa/tftp.h>
#include <asl.h>
#include <assert.h>
#include <atm/atm_types.h>
#include <bank/bank_types.h>
#include <bitstring.h>
#include <bootparams.h>
#include <bootstrap.h>
#include <bsm/audit.h>
#include <bsm/audit_domain.h>
#include <bsm/audit_errno.h>
#include <bsm/audit_fcntl.h>
#include <bsm/audit_filter.h>
#include <bsm/audit_internal.h>
#include <bsm/audit_kevents.h>
#include <bsm/audit_record.h>
#include <bsm/audit_session.h>
#include <bsm/audit_socket_type.h>
#include <bsm/audit_uevents.h>
#include <bsm/libbsm.h>
#include <cache.h>
#include <cache_callbacks.h>
#include <checkint.h>
#include <complex.h>
#include <copyfile.h>
#include <corpses/task_corpse.h>
#include <cpio.h>
#include <crt_externs.h>
#include <ctype.h>
#include <db.h>
#include <default_pager/default_pager_types.h>
#include <device/device_port.h>
#include <device/device_types.h>
#include <dirent.h>
#include <disktab.h>
#include <dispatch/dispatch.h>
#include <dispatch/introspection.h>
#include <dlfcn.h>
#include <dns.h>
#include <dns_sd.h>
#include <dns_util.h>
#include <err.h>
#include <errno.h>
#include <execinfo.h>
#include <fcntl.h>
#include <fenv.h>
#include <float.h>
#include <fmtmsg.h>
#include <fnmatch.h>
#include <fsproperties.h>
#include <fstab.h>
#include <fts.h>
#include <ftw.h>
#include <get_compat.h>
#include <gethostuuid.h>
#include <getopt.h>
#include <glob.h>
#include <grp.h>
#include <hfs/hfs_format.h>
#include <hfs/hfs_mount.h>
#include <hfs/hfs_unistr.h>
#include <ifaddrs.h>
#include <inttypes.h>
#include <iso646.h>
#include <kern/exc_guard.h>
#include <kern/exc_resource.h>
#include <kern/kcdata.h>
#include <kern/kern_cdata.h>
#include <langinfo.h>
#include <launch.h>
#include <libc.h>
#include <libgen.h>
#include <libkern/OSAtomic.h>
#include <libkern/OSAtomicDeprecated.h>
#include <libkern/OSAtomicQueue.h>
#include <libkern/OSByteOrder.h>
#include <libkern/OSCacheControl.h>
#include <libkern/OSDebug.h>
#include <libkern/OSKextLib.h>
#include <libkern/OSReturn.h>
#include <libkern/OSSpinLockDeprecated.h>
#include <libkern/OSThermalNotification.h>
#include <libkern/OSTypes.h>
#include <libkern/_OSByteOrder.h>
#include <libkern/arm/OSByteOrder.h>
#include <libkern/arm/_OSByteOrder.h>
#include <libkern/i386/OSByteOrder.h>
#include <libkern/i386/_OSByteOrder.h>
#include <libkern/machine/OSByteOrder.h>
#include <libproc.h>
#include <libunwind.h>
#include <limits.h>
#include <locale.h>
#include <mach-o/arch.h>
#include <mach-o/arm/reloc.h>
#include <mach-o/arm64/reloc.h>
#include <mach-o/compact_unwind_encoding.h>
#include <mach-o/dyld.h>
#include <mach-o/dyld_images.h>
#include <mach-o/fat.h>
#include <mach-o/fixup-chains.h>
#include <mach-o/getsect.h>
#include <mach-o/ldsyms.h>
#include <mach-o/loader.h>
#include <mach-o/nlist.h>
#include <mach-o/ranlib.h>
#include <mach-o/reloc.h>
#include <mach-o/stab.h>
#include <mach-o/swap.h>
#include <mach-o/utils.h>
#include <mach-o/x86_64/reloc.h>
#include <mach/arm/_structs.h>
#include <mach/arm/asm.h>
#include <mach/arm/boolean.h>
#include <mach/arm/exception.h>
#include <mach/arm/kern_return.h>
#include <mach/arm/ndr_def.h>
#include <mach/arm/processor_info.h>
#include <mach/arm/rpc.h>
#include <mach/arm/sdt_isa.h>
#include <mach/arm/thread_state.h>
#include <mach/arm/thread_status.h>
#include <mach/arm/traps.h>
#include <mach/arm/vm_param.h>
#include <mach/arm/vm_types.h>
#include <mach/arm64/asm.h>
#include <mach/audit_triggers_types.h>
#include <mach/boolean.h>
#include <mach/bootstrap.h>
#include <mach/clock.h>
#include <mach/clock_priv.h>
#include <mach/clock_reply.h>
#include <mach/clock_types.h>
#include <mach/doubleagent_types.h>
#include <mach/dyld_kernel.h>
#include <mach/dyld_pager.h>
#include <mach/error.h>
#include <mach/exc.h>
#include <mach/exception.h>
#include <mach/exception_types.h>
#include <mach/host_info.h>
#include <mach/host_notify.h>
#include <mach/host_priv.h>
#include <mach/host_reboot.h>
#include <mach/host_security.h>
#include <mach/host_special_ports.h>
#include <mach/i386/_structs.h>
#include <mach/i386/asm.h>
#include <mach/i386/boolean.h>
#include <mach/i386/exception.h>
#include <mach/i386/fp_reg.h>
#include <mach/i386/kern_return.h>
#include <mach/i386/processor_info.h>
#include <mach/i386/rpc.h>
#include <mach/i386/sdt_isa.h>
#include <mach/i386/thread_state.h>
#include <mach/i386/thread_status.h>
#include <mach/i386/vm_param.h>
#include <mach/i386/vm_types.h>
#include <mach/kern_return.h>
#include <mach/kmod.h>
#include <mach/mach.h>
#include <mach/mach_error.h>
#include <mach/mach_host.h>
#include <mach/mach_init.h>
#include <mach/mach_interface.h>
#include <mach/mach_param.h>
#include <mach/mach_port.h>
#include <mach/mach_right.h>
#include <mach/mach_syscalls.h>
#include <mach/mach_time.h>
#include <mach/mach_traps.h>
#include <mach/mach_types.h>
#include <mach/mach_vm.h>
#include <mach/mach_voucher.h>
#include <mach/mach_voucher_types.h>
#include <mach/machine.h>
#include <mach/machine/_structs.h>
#include <mach/machine/asm.h>
#include <mach/machine/boolean.h>
#include <mach/machine/exception.h>
#include <mach/machine/kern_return.h>
#include <mach/machine/processor_info.h>
#include <mach/machine/rpc.h>
#include <mach/machine/sdt.h>
#include <mach/machine/sdt_isa.h>
#include <mach/machine/thread_state.h>
#include <mach/machine/thread_status.h>
#include <mach/machine/vm_param.h>
#include <mach/machine/vm_types.h>
#include <mach/memory_entry.h>
#include <mach/memory_object_types.h>
#include <mach/message.h>
#include <mach/mig.h>
#include <mach/mig_errors.h>
#include <mach/mig_strncpy_zerofill_support.h>
#include <mach/mig_voucher_support.h>
#include <mach/ndr.h>
#include <mach/notify.h>
#include <mach/policy.h>
#include <mach/port.h>
#include <mach/port_obj.h>
#include <mach/processor.h>
#include <mach/processor_info.h>
#include <mach/processor_set.h>
#include <mach/rpc.h>
#include <mach/sdt.h>
#include <mach/semaphore.h>
#include <mach/shared_memory_server.h>
#include <mach/shared_region.h>
#include <mach/std_types.h>
#include <mach/sync.h>
#include <mach/sync_policy.h>
#include <mach/task.h>
#include <mach/task_info.h>
#include <mach/task_inspect.h>
#include <mach/task_policy.h>
#include <mach/task_special_ports.h>
#include <mach/thread_act.h>
#include <mach/thread_info.h>
#include <mach/thread_policy.h>
#include <mach/thread_special_ports.h>
#include <mach/thread_state.h>
#include <mach/thread_status.h>
#include <mach/thread_switch.h>
#include <mach/time_value.h>
#include <mach/vm_attributes.h>
#include <mach/vm_behavior.h>
#include <mach/vm_inherit.h>
#include <mach/vm_map.h>
#include <mach/vm_page_size.h>
#include <mach/vm_param.h>
#include <mach/vm_prot.h>
#include <mach/vm_purgable.h>
#include <mach/vm_region.h>
#include <mach/vm_statistics.h>
#include <mach/vm_sync.h>
#include <mach/vm_task.h>
#include <mach/vm_types.h>
#include <mach_debug/hash_info.h>
#include <mach_debug/ipc_info.h>
#include <mach_debug/lockgroup_info.h>
#include <mach_debug/mach_debug.h>
#include <mach_debug/mach_debug_types.h>
#include <mach_debug/page_info.h>
#include <mach_debug/vm_info.h>
#include <mach_debug/zone_info.h>
#include <machine/_endian.h>
#include <machine/_limits.h>
#include <machine/_mcontext.h>
#include <machine/_param.h>
#include <machine/_types.h>
#include <machine/byte_order.h>
#include <machine/endian.h>
#include <machine/fasttrap_isa.h>
#include <machine/limits.h>
#include <machine/param.h>
#include <machine/profile.h>
#include <machine/signal.h>
#include <machine/types.h>
#include <machine/vmparam.h>
#include <malloc/_malloc.h>
#include <malloc/_malloc_type.h>
#include <malloc/_platform.h>
#include <malloc/_ptrcheck.h>
#include <malloc/malloc.h>
#include <math.h>
#include <membership.h>
#include <memory.h>
#include <miscfs/devfs/devfs.h>
#include <miscfs/union/union.h>
#include <monetary.h>
#include <monitor.h>
#include <nameser.h>
#include <ndbm.h>
#include <net/bpf.h>
#include <net/dlil.h>
#include <net/ethernet.h>
#include <net/if.h>
#include <net/if_arp.h>
#include <net/if_dl.h>
#include <net/if_llc.h>
#include <net/if_media.h>
#include <net/if_mib.h>
#include <net/if_types.h>
#include <net/if_utun.h>
#include <net/if_var.h>
#include <net/ipsec_offload.h>
#include <net/kext_net.h>
#include <net/ndrv.h>
#include <net/net_kev.h>
#include <net/pfkeyv2.h>
#include <net/route.h>
#include <netdb.h>
#include <netinet/bootp.h>
#include <netinet/icmp6.h>
#include <netinet/icmp_var.h>
#include <netinet/if_ether.h>
#include <netinet/igmp.h>
#include <netinet/igmp_var.h>
#include <netinet/in.h>
#include <netinet/in_pcb.h>
#include <netinet/in_systm.h>
#include <netinet/in_var.h>
#include <netinet/ip.h>
#include <netinet/ip6.h>
#include <netinet/ip_icmp.h>
#include <netinet/ip_var.h>
#include <netinet/tcp.h>
#include <netinet/tcp_fsm.h>
#include <netinet/tcp_seq.h>
#include <netinet/tcp_timer.h>
#include <netinet/tcp_var.h>
#include <netinet/tcpip.h>
#include <netinet/udp.h>
#include <netinet/udp_var.h>
#include <netinet6/ah.h>
#include <netinet6/esp.h>
#include <netinet6/in6_var.h>
#include <netinet6/ipcomp.h>
#include <netinet6/ipsec.h>
#include <netinet6/nd6.h>
#include <netinet6/raw_ip6.h>
#include <netinet6/scope6_var.h>
#include <netkey/keysock.h>
#include <networkext/ne_socket.h>
#include <nl_types.h>
#include <notify.h>
#include <notify_keys.h>
#include <ntsid.h>
#include <os/activity.h>
#include <os/arch/arm64.h>
#include <os/atomic.h>
#include <os/availability.h>
#include <os/base.h>
#include <os/clock.h>
#include <os/lock.h>
#include <os/lockdown_mode.h>
#include <os/log.h>
#include <os/object.h>
#include <os/os_sync_wait_on_address.h>
#include <os/overflow.h>
#include <os/proc.h>
#include <os/security_config.h>
#include <os/signpost.h>
#include <os/trace.h>
#include <os/trace_base.h>
#include <os/workgroup.h>
#include <paths.h>
#include <poll.h>
#include <printerdb.h>
#include <printf.h>
#include <protocols/routed.h>
#include <protocols/rwhod.h>
#include <protocols/talkd.h>
#include <pthread.h>
#include <pthread/introspection.h>
#include <pthread/pthread.h>
#include <pthread/pthread_impl.h>
#include <pthread/pthread_spis.h>
#include <pthread/qos.h>
#include <pthread/sched.h>
#include <pthread/spawn.h>
#include <pthread/stack_np.h>
#include <pthread_impl.h>
#include <pthread_spis.h>
#include <pwd.h>
#include <readpassphrase.h>
#include <regex.h>
#include <removefile.h>
#include <resolv.h>
#include <rpc/auth.h>
#include <rpc/auth_unix.h>
#include <rpc/clnt.h>
#include <rpc/pmap_clnt.h>
#include <rpc/pmap_prot.h>
#include <rpc/pmap_rmt.h>
#include <rpc/svc.h>
#include <rpc/svc_auth.h>
#include <rpc/types.h>
#include <rpc/xdr.h>
#include <rpcsvc/ypclnt.h>
#include <rune.h>
#include <runetype.h>
#include <sandbox.h>
#include <sched.h>
#include <search.h>
#include <secure/_common.h>
#include <secure/_stdio.h>
#include <secure/_string.h>
#include <secure/_strings.h>
#include <security/audit/audit_ioctl.h>
#include <security/openpam_attr.h>
#include <security/openpam_version.h>
#include <security/pam_appl.h>
#include <security/pam_constants.h>
#include <security/pam_modules.h>
#include <security/pam_types.h>
#include <semaphore.h>
#include <servers/bootstrap.h>
#include <servers/bootstrap_defs.h>
#include <servers/ls_defs.h>
#include <servers/netname.h>
#include <servers/netname_defs.h>
#include <servers/nm_defs.h>
#include <setjmp.h>
#include <sgtty.h>
#include <signal.h>
#include <spawn.h>
#include <stab.h>
#include <standards.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <strhash.h>
#include <string.h>
#include <string_x86.h>
#include <stringlist.h>
#include <strings.h>
#include <struct.h>
#include <sys/__endian.h>
#include <sys/_endian.h>
#include <sys/_posix_availability.h>
#include <sys/_pthread/_pthread_attr_t.h>
#include <sys/_pthread/_pthread_cond_t.h>
#include <sys/_pthread/_pthread_condattr_t.h>
#include <sys/_pthread/_pthread_key_t.h>
#include <sys/_pthread/_pthread_mutex_t.h>
#include <sys/_pthread/_pthread_mutexattr_t.h>
#include <sys/_pthread/_pthread_once_t.h>
#include <sys/_pthread/_pthread_rwlock_t.h>
#include <sys/_pthread/_pthread_rwlockattr_t.h>
#include <sys/_pthread/_pthread_t.h>
#include <sys/_pthread/_pthread_types.h>
#include <sys/_select.h>
#include <sys/_structs.h>
#include <sys/_symbol_aliasing.h>
#include <sys/_types.h>
#include <sys/_types/_blkcnt_t.h>
#include <sys/_types/_blksize_t.h>
#include <sys/_types/_caddr_t.h>
#include <sys/_types/_clock_t.h>
#include <sys/_types/_ct_rune_t.h>
#include <sys/_types/_dev_t.h>
#include <sys/_types/_errno_t.h>
#include <sys/_types/_fd_clr.h>
#include <sys/_types/_fd_copy.h>
#include <sys/_types/_fd_def.h>
#include <sys/_types/_fd_isset.h>
#include <sys/_types/_fd_set.h>
#include <sys/_types/_fd_setsize.h>
#include <sys/_types/_fd_zero.h>
#include <sys/_types/_filesec_t.h>
#include <sys/_types/_fsblkcnt_t.h>
#include <sys/_types/_fsfilcnt_t.h>
#include <sys/_types/_fsid_t.h>
#include <sys/_types/_fsobj_id_t.h>
#include <sys/_types/_gid_t.h>
#include <sys/_types/_graftdmg_un.h>
#include <sys/_types/_guid_t.h>
#include <sys/_types/_id_t.h>
#include <sys/_types/_in_addr_t.h>
#include <sys/_types/_in_port_t.h>
#include <sys/_types/_ino64_t.h>
#include <sys/_types/_ino_t.h>
#include <sys/_types/_int16_t.h>
#include <sys/_types/_int32_t.h>
#include <sys/_types/_int64_t.h>
#include <sys/_types/_int8_t.h>
#include <sys/_types/_intptr_t.h>
#include <sys/_types/_iovec_t.h>
#include <sys/_types/_key_t.h>
#include <sys/_types/_mach_port_t.h>
#include <sys/_types/_mbstate_t.h>
#include <sys/_types/_mode_t.h>
#include <sys/_types/_mount_t.h>
#include <sys/_types/_nlink_t.h>
#include <sys/_types/_null.h>
#include <sys/_types/_o_dsync.h>
#include <sys/_types/_o_sync.h>
#include <sys/_types/_off_t.h>
#include <sys/_types/_offsetof.h>
#include <sys/_types/_os_inline.h>
#include <sys/_types/_pid_t.h>
#include <sys/_types/_posix_vdisable.h>
#include <sys/_types/_ptrdiff_t.h>
#include <sys/_types/_rsize_t.h>
#include <sys/_types/_rune_t.h>
#include <sys/_types/_s_ifmt.h>
#include <sys/_types/_sa_family_t.h>
#include <sys/_types/_seek_set.h>
#include <sys/_types/_sigaltstack.h>
#include <sys/_types/_sigset_t.h>
#include <sys/_types/_size_t.h>
#include <sys/_types/_socklen_t.h>
#include <sys/_types/_ssize_t.h>
#include <sys/_types/_suseconds_t.h>
#include <sys/_types/_time_t.h>
#include <sys/_types/_timespec.h>
#include <sys/_types/_timeval.h>
#include <sys/_types/_timeval32.h>
#include <sys/_types/_timeval64.h>
#include <sys/_types/_u_char.h>
#include <sys/_types/_u_int.h>
#include <sys/_types/_u_int16_t.h>
#include <sys/_types/_u_int32_t.h>
#include <sys/_types/_u_int64_t.h>
#include <sys/_types/_u_int8_t.h>
#include <sys/_types/_u_short.h>
#include <sys/_types/_ucontext.h>
#include <sys/_types/_ucontext64.h>
#include <sys/_types/_uid_t.h>
#include <sys/_types/_uintptr_t.h>
#include <sys/_types/_useconds_t.h>
#include <sys/_types/_uuid_t.h>
#include <sys/_types/_va_list.h>
#include <sys/_types/_vnode_t.h>
#include <sys/_types/_wchar_t.h>
#include <sys/_types/_wint_t.h>
#include <sys/acct.h>
#include <sys/acl.h>
#include <sys/aio.h>
#include <sys/appleapiopts.h>
#include <sys/attr.h>
#include <sys/buf.h>
#include <sys/cdefs.h>
#include <sys/clonefile.h>
#include <sys/commpage.h>
#include <sys/conf.h>
#include <sys/constrained_ctypes.h>
#include <sys/dir.h>
#include <sys/dirent.h>
#include <sys/disk.h>
#include <sys/dkstat.h>
#include <sys/domain.h>
#include <sys/dtrace.h>
#include <sys/dtrace_glue.h>
#include <sys/endian.h>
#include <sys/errno.h>
#include <sys/ev.h>
#include <sys/event.h>
#include <sys/fasttrap.h>
#include <sys/fasttrap_isa.h>
#include <sys/fcntl.h>
#include <sys/file.h>
#include <sys/filedesc.h>
#include <sys/fileport.h>
#include <sys/filio.h>
#include <sys/fsgetpath.h>
#include <sys/gmon.h>
#include <sys/ioccom.h>
#include <sys/ioctl.h>
#include <sys/ioctl_compat.h>
#include <sys/ipc.h>
#include <sys/kauth.h>
#include <sys/kdebug.h>
#include <sys/kdebug_signpost.h>
#include <sys/kern_control.h>
#include <sys/kern_event.h>
#include <sys/kernel.h>
#include <sys/kernel_types.h>
#include <sys/lctx.h>
#include <sys/loadable_fs.h>
#include <sys/lock.h>
#include <sys/lockf.h>
#include <sys/lockstat.h>
#include <sys/log_data.h>
#include <sys/malloc.h>
#include <sys/mbuf.h>
#include <sys/mman.h>
#include <sys/mount.h>
#include <sys/msg.h>
#include <sys/msgbuf.h>
#include <sys/netport.h>
#include <sys/param.h>
#include <sys/paths.h>
#include <sys/pipe.h>
#include <sys/poll.h>
#include <sys/posix_sem.h>
#include <sys/posix_shm.h>
#include <sys/proc.h>
#include <sys/proc_info.h>
#include <sys/protosw.h>
#include <sys/ptrace.h>
#include <sys/qos.h>
#include <sys/queue.h>
#include <sys/quota.h>
#include <sys/random.h>
#include <sys/rbtree.h>
#include <sys/reboot.h>
#include <sys/resource.h>
#include <sys/resourcevar.h>
#include <sys/sbuf.h>
#include <sys/sdt.h>
#include <sys/select.h>
#include <sys/sem.h>
#include <sys/semaphore.h>
#include <sys/shm.h>
#include <sys/signal.h>
#include <sys/signalvar.h>
#include <sys/snapshot.h>
#include <sys/socket.h>
#include <sys/socketvar.h>
#include <sys/sockio.h>
#include <sys/spawn.h>
#include <sys/stat.h>
#include <sys/statvfs.h>
#include <sys/stdio.h>
#include <sys/sys_domain.h>
#include <sys/syscall.h>
#include <sys/sysctl.h>
#include <sys/syslimits.h>
#include <sys/syslog.h>
#include <sys/termios.h>
#include <sys/time.h>
#include <sys/timeb.h>
#include <sys/times.h>
#include <sys/timex.h>
#include <sys/trace.h>
#include <sys/tty.h>
#include <sys/ttychars.h>
#include <sys/ttycom.h>
#include <sys/ttydefaults.h>
#include <sys/ttydev.h>
#include <sys/types.h>
#include <sys/ucontext.h>
#include <sys/ucred.h>
#include <sys/uio.h>
#include <sys/un.h>
#include <sys/unistd.h>
#include <sys/unpcb.h>
#include <sys/user.h>
#include <sys/utfconv.h>
#include <sys/utsname.h>
#include <sys/vadvise.h>
#include <sys/vcmd.h>
#include <sys/vm.h>
#include <sys/vmmeter.h>
#include <sys/vmparam.h>
#include <sys/vnode.h>
#include <sys/vnode_if.h>
#include <sys/vsock.h>
#include <sys/vstat.h>
#include <sys/wait.h>
#include <sys/xattr.h>
#include <sysdir.h>
#include <sysexits.h>
#include <syslog.h>
#include <tar.h>
#include <termios.h>
#include <tgmath.h>
#include <time.h>
#include <timeconv.h>
#include <timingsafe.h>
#include <ttyent.h>
#include <tzfile.h>
#include <ulimit.h>
#include <unistd.h>
#include <unwind.h>
#include <usbuf.h>
#include <utime.h>
#include <utmp.h>
#include <utmpx.h>
#include <uuid/uuid.h>
#include <vis.h>
#include <voucher/ipc_pthread_priority_types.h>
#include <vproc.h>
#include <wchar.h>
#include <wctype.h>
#include <wordexp.h>
#include <xattr_flags.h>
#include <xlocale.h>
#include <xlocale/___wctype.h>
#include <xlocale/_ctype.h>
#include <xlocale/_inttypes.h>
#include <xlocale/_langinfo.h>
#include <xlocale/_monetary.h>
#include <xlocale/_regex.h>
#include <xlocale/_stdio.h>
#include <xlocale/_stdlib.h>
#include <xlocale/_string.h>
#include <xlocale/_time.h>
#include <xlocale/_wchar.h>
#include <xlocale/_wctype.h>
#include <xpc/availability.h>
#include <xpc/xpc.h>
