/* Unit tests for the i386 (32-bit) decode path added by ocerz_decode_mode().
 *
 * Every row was generated by running the real capstone 5.0.7 disassembler as
 * an oracle and only accepting the row when capstone's instruction LENGTH
 * agreed with ours; capstone's own rendering is kept in each row so the
 * provenance is visible, and the length embedded in that string is re-checked
 * here at run time.  The test itself has no capstone dependency.
 *
 * The `want` string is the full canonical record -- every X86Insn and
 * X86Operand field the decoder fills in -- so any change to any of them shows
 * up as a failure rather than being silently checked-around.
 *
 * The 64-bit rows are not decoration: they pin the long-mode behaviour of
 * exactly the sites the mode seam threads through, so a future edit that
 * "helpfully" makes one of them mode-aware fails here as well as in decodiff.
 */
#include "ocerz/decode.h"
#include "ocerz/cpu.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct Case32 {
    int mode32;
    uint64_t rip;
    const char *note;
    const char *capstone;   /* verbatim capstone output, "mnem ops (size)" */
    uint8_t bytes[12];
    int nbytes;
    const char *want;
} Case32;

#define B(...) { __VA_ARGS__ }

static const Case32 cases[] = {
    { .mode32 = 1, .rip = 0x1000ull, .note = "mov eax, [0x18] -- the flat 32-bit moffs",
      .capstone = "mov eax, dword ptr [0x18] (5)",
      .bytes = B(0xa1, 0x18, 0x00, 0x00, 0x00), .nbytes = 5,
      .want = "op=mov len=5 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=24 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "mov eax, fs:[0x18] -- the TEB read",
      .capstone = "mov eax, dword ptr fs:[0x18] (6)",
      .bytes = B(0x64, 0xa1, 0x18, 0x00, 0x00, 0x00), .nbytes = 6,
      .want = "op=mov len=6 opsize=4 addrsize=4 seg=1 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=24 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "moffs shrinks to 16 bits under 0x67",
      .capstone = "mov eax, dword ptr [0x1234] (4)",
      .bytes = B(0x67, 0xa1, 0x34, 0x12), .nbytes = 4,
      .want = "op=mov len=4 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=4660 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "mod=00 rm=101 is absolute, NOT rip-relative",
      .capstone = "mov eax, dword ptr [0x12345678] (6)",
      .bytes = B(0x8b, 0x05, 0x78, 0x56, 0x34, 0x12), .nbytes = 6,
      .want = "op=mov len=6 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=305419896 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "[ebp+disp8]",
      .capstone = "mov eax, dword ptr [ebp + 8] (3)",
      .bytes = B(0x8b, 0x45, 0x08), .nbytes = 3,
      .want = "op=mov len=3 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=5 index=255 scale=0 riprel=0 disp=8 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "SIB with no base",
      .capstone = "mov eax, dword ptr [ecx*4 + 0x12345678] (7)",
      .bytes = B(0x8b, 0x04, 0x8d, 0x78, 0x56, 0x34, 0x12), .nbytes = 7,
      .want = "op=mov len=7 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=255 index=1 scale=2 riprel=0 disp=305419896 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "jmp dword [eax] -- near branch is 4 bytes wide",
      .capstone = "jmp dword ptr [eax] (2)",
      .bytes = B(0xff, 0x20), .nbytes = 2,
      .want = "op=jmp len=2 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=4 reg=0 size=4 high8=0 base=0 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "jmp eax",
      .capstone = "jmp eax (2)",
      .bytes = B(0xff, 0xe0), .nbytes = 2,
      .want = "op=jmp len=2 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "jmp ax -- 0x66 DOES apply to near branches in 32-bit",
      .capstone = "jmp ax (3)",
      .bytes = B(0x66, 0xff, 0xe0), .nbytes = 3,
      .want = "op=jmp len=3 opsize=2 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=1 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "call eax",
      .capstone = "call eax (2)",
      .bytes = B(0xff, 0xd0), .nbytes = 2,
      .want = "op=call len=2 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "call dword [abs]",
      .capstone = "call dword ptr [0x12345678] (6)",
      .bytes = B(0xff, 0x15, 0x78, 0x56, 0x34, 0x12), .nbytes = 6,
      .want = "op=call len=6 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=4 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=305419896 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "push eax -- 4-byte stack slot",
      .capstone = "push eax (1)",
      .bytes = B(0x50), .nbytes = 1,
      .want = "op=push len=1 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "push ax",
      .capstone = "push ax (2)",
      .bytes = B(0x66, 0x50), .nbytes = 2,
      .want = "op=push len=2 opsize=2 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=1 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "pop eax",
      .capstone = "pop eax (1)",
      .bytes = B(0x58), .nbytes = 1,
      .want = "op=pop len=1 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "push imm32",
      .capstone = "push 0x12345678 (5)",
      .bytes = B(0x68, 0x78, 0x56, 0x34, 0x12), .nbytes = 5,
      .want = "op=push len=5 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x12345678" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "push imm8",
      .capstone = "push 0x7f (2)",
      .bytes = B(0x6a, 0x7f), .nbytes = 2,
      .want = "op=push len=2 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x7f" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "push dword [eax]",
      .capstone = "push dword ptr [eax] (2)",
      .bytes = B(0xff, 0x30), .nbytes = 2,
      .want = "op=push len=2 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=4 reg=0 size=4 high8=0 base=0 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "pop dword [eax]",
      .capstone = "pop dword ptr [eax] (2)",
      .bytes = B(0x8f, 0x00), .nbytes = 2,
      .want = "op=pop len=2 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=4 reg=0 size=4 high8=0 base=0 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "ret",
      .capstone = "ret (1)",
      .bytes = B(0xc3), .nbytes = 1,
      .want = "op=ret len=1 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "ret 8",
      .capstone = "ret 8 (3)",
      .bytes = B(0xc2, 0x08, 0x00), .nbytes = 3,
      .want = "op=ret len=3 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x8" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "leave",
      .capstone = "leave (1)",
      .bytes = B(0xc9), .nbytes = 1,
      .want = "op=leave len=1 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "pushfd",
      .capstone = "pushfd (1)",
      .bytes = B(0x9c), .nbytes = 1,
      .want = "op=pushf len=1 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "popfd",
      .capstone = "popfd (1)",
      .bytes = B(0x9d), .nbytes = 1,
      .want = "op=popf len=1 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "jmp rel32",
      .capstone = "jmp 0x1234667d (5)",
      .bytes = B(0xe9, 0x78, 0x56, 0x34, 0x12), .nbytes = 5,
      .want = "op=jmp len=5 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x1234667d" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "jmp rel16 -- 0x66 shortens the displacement",
      .capstone = "jmp 0x2238 (4)",
      .bytes = B(0x66, 0xe9, 0x34, 0x12), .nbytes = 4,
      .want = "op=jmp len=4 opsize=2 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x2238" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "call rel32",
      .capstone = "call 0x1234667d (5)",
      .bytes = B(0xe8, 0x78, 0x56, 0x34, 0x12), .nbytes = 5,
      .want = "op=call len=5 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x1234667d" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "jmp rel8",
      .capstone = "jmp 0x1007 (2)",
      .bytes = B(0xeb, 0x05), .nbytes = 2,
      .want = "op=jmp len=2 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x1007" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "je rel8",
      .capstone = "je 0x1007 (2)",
      .bytes = B(0x74, 0x05), .nbytes = 2,
      .want = "op=jcc len=2 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=4 nops=1 | op0 kind=5 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x1007" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "je rel32",
      .capstone = "je 0x1234667e (6)",
      .bytes = B(0x0f, 0x84, 0x78, 0x56, 0x34, 0x12), .nbytes = 6,
      .want = "op=jcc len=6 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=4 nops=1 | op0 kind=5 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x1234667e" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "je rel16",
      .capstone = "je 0x2239 (5)",
      .bytes = B(0x66, 0x0f, 0x84, 0x34, 0x12), .nbytes = 5,
      .want = "op=jcc len=5 opsize=2 addrsize=4 seg=0 rep=0 lock=0 cc=4 nops=1 | op0 kind=5 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x2239" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "jecxz",
      .capstone = "jecxz 0x1000 (2)",
      .bytes = B(0xe3, 0xfe), .nbytes = 2,
      .want = "op=jrcxz len=2 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x1000" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "mov al, ah -- AH exists only in 32-bit mode",
      .capstone = "mov al, ah (2)",
      .bytes = B(0x88, 0xe0), .nbytes = 2,
      .want = "op=mov len=2 opsize=1 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=1 reg=0 size=1 high8=1 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "mov ah, al",
      .capstone = "mov ah, al (2)",
      .bytes = B(0x8a, 0xe0), .nbytes = 2,
      .want = "op=mov len=2 opsize=1 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=1 high8=1 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=1 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "mov ah, imm8",
      .capstone = "mov ah, 0x12 (2)",
      .bytes = B(0xb4, 0x12), .nbytes = 2,
      .want = "op=mov len=2 opsize=1 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=1 high8=1 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=5 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x12" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "mov eax, imm32",
      .capstone = "mov eax, 0x12345678 (5)",
      .bytes = B(0xb8, 0x78, 0x56, 0x34, 0x12), .nbytes = 5,
      .want = "op=mov len=5 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=5 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x12345678" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "mov ax, imm16",
      .capstone = "mov ax, 0x1234 (4)",
      .bytes = B(0x66, 0xb8, 0x34, 0x12), .nbytes = 4,
      .want = "op=mov len=4 opsize=2 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=5 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x1234" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "add eax, 1",
      .capstone = "add eax, 1 (3)",
      .bytes = B(0x83, 0xc0, 0x01), .nbytes = 3,
      .want = "op=add len=3 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=5 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x1" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "mov dword [ebp-4], 1",
      .capstone = "mov dword ptr [ebp - 4], 1 (7)",
      .bytes = B(0xc7, 0x45, 0xfc, 0x01, 0x00, 0x00, 0x00), .nbytes = 7,
      .want = "op=mov len=7 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=4 reg=0 size=4 high8=0 base=5 index=255 scale=0 riprel=0 disp=-4 imm=0x0 | op1 kind=5 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x1" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "16-bit addressing: displacement-only at mod=00 rm=110",
      .capstone = "mov eax, dword ptr [0x1234] (5)",
      .bytes = B(0x67, 0x8b, 0x06, 0x34, 0x12), .nbytes = 5,
      .want = "op=mov len=5 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=4660 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "16-bit addressing: [bx+si]",
      .capstone = "mov eax, dword ptr [bx + si] (3)",
      .bytes = B(0x67, 0x8b, 0x00), .nbytes = 3,
      .want = "op=mov len=3 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=3 index=6 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "16-bit addressing: [bx+di+disp8]",
      .capstone = "mov eax, dword ptr [bx + di + 0x10] (4)",
      .bytes = B(0x67, 0x8b, 0x41, 0x10), .nbytes = 4,
      .want = "op=mov len=4 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=3 index=7 scale=0 riprel=0 disp=16 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "16-bit addressing: [bp+disp16]",
      .capstone = "mov eax, dword ptr [bp + 0x1234] (5)",
      .bytes = B(0x67, 0x8b, 0x86, 0x34, 0x12), .nbytes = 5,
      .want = "op=mov len=5 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=5 index=255 scale=0 riprel=0 disp=4660 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "16-bit addressing: [bx]",
      .capstone = "mov eax, dword ptr [bx] (3)",
      .bytes = B(0x67, 0x8b, 0x07), .nbytes = 3,
      .want = "op=mov len=3 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=3 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "16-bit addressing with a 16-bit operand",
      .capstone = "mov ax, word ptr [bx] (4)",
      .bytes = B(0x67, 0x66, 0x8b, 0x07), .nbytes = 4,
      .want = "op=mov len=4 opsize=2 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=2 high8=0 base=3 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "16-bit addressing: [si+disp8]",
      .capstone = "mov ebx, dword ptr [si + 8] (4)",
      .bytes = B(0x67, 0x8b, 0x5c, 0x08), .nbytes = 4,
      .want = "op=mov len=4 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=3 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=6 index=255 scale=0 riprel=0 disp=8 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "rep movsd",
      .capstone = "rep movsd dword ptr es:[edi], dword ptr [esi] (2)",
      .bytes = B(0xf3, 0xa5), .nbytes = 2,
      .want = "op=movs len=2 opsize=4 addrsize=4 seg=0 rep=1 lock=0 cc=0 nops=0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "0x40 is REX here, not INC eax",
      .capstone = "nop (2)",
      .bytes = B(0x40, 0x90), .nbytes = 2,
      .want = "op=nop len=2 opsize=0 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "add rax, rbx",
      .capstone = "add rax, rbx (3)",
      .bytes = B(0x48, 0x01, 0xd8), .nbytes = 3,
      .want = "op=add len=3 opsize=8 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=8 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=1 reg=3 size=8 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "moffs follows the 32-bit address size",
      .capstone = "mov eax, dword ptr [0x4030201] (6)",
      .bytes = B(0x67, 0xa1, 0x01, 0x02, 0x03, 0x04), .nbytes = 6,
      .want = "op=mov len=6 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=67305985 imm=0x0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "moffs64",
      .capstone = "movabs eax, dword ptr [0x807060504030201] (9)",
      .bytes = B(0xa1, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08), .nbytes = 9,
      .want = "op=mov len=9 opsize=4 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=578437695752307201 imm=0x0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "mod=00 rm=101 IS rip-relative here",
      .capstone = "mov eax, dword ptr [rip + 0x12345678] (6)",
      .bytes = B(0x8b, 0x05, 0x78, 0x56, 0x34, 0x12), .nbytes = 6,
      .want = "op=mov len=6 opsize=4 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=1 disp=5674133118 imm=0x0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "jmp qword [rax] -- forced to 64 bits",
      .capstone = "jmp qword ptr [rax] (2)",
      .bytes = B(0xff, 0x20), .nbytes = 2,
      .want = "op=jmp len=2 opsize=8 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=4 reg=0 size=8 high8=0 base=0 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "0x66 is IGNORED on a near branch in 64-bit mode",
      .capstone = "jmp rax (3)",
      .bytes = B(0x66, 0xff, 0xe0), .nbytes = 3,
      .want = "op=jmp len=3 opsize=8 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=1 reg=0 size=8 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "push rax -- 8-byte stack slot",
      .capstone = "push rax (1)",
      .bytes = B(0x50), .nbytes = 1,
      .want = "op=push len=1 opsize=8 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=1 reg=0 size=8 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "push ax",
      .capstone = "push ax (2)",
      .bytes = B(0x66, 0x50), .nbytes = 2,
      .want = "op=push len=2 opsize=2 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=1 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "push imm8, 8-byte slot",
      .capstone = "push 0x7f (2)",
      .bytes = B(0x6a, 0x7f), .nbytes = 2,
      .want = "op=push len=2 opsize=8 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=8 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x7f" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "ret",
      .capstone = "ret (1)",
      .bytes = B(0xc3), .nbytes = 1,
      .want = "op=ret len=1 opsize=8 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "0x66 ret: HEAD reports the 8-byte form, pinned here",
      .capstone = "ret (2)",
      .bytes = B(0x66, 0xc3), .nbytes = 2,
      .want = "op=ret len=2 opsize=8 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "leave",
      .capstone = "leave (1)",
      .bytes = B(0xc9), .nbytes = 1,
      .want = "op=leave len=1 opsize=8 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "pushfq",
      .capstone = "pushfq (1)",
      .bytes = B(0x9c), .nbytes = 1,
      .want = "op=pushf len=1 opsize=8 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "jmp rel32 -- 0x66 does not shorten it",
      .capstone = "jmp 0x14000223a (6)",
      .bytes = B(0x66, 0xe9, 0x34, 0x12, 0x00, 0x00), .nbytes = 6,
      .want = "op=jmp len=6 opsize=8 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=8 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x14000223a" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "jrcxz",
      .capstone = "jrcxz 0x140001000 (2)",
      .bytes = B(0xe3, 0xfe), .nbytes = 2,
      .want = "op=jrcxz len=2 opsize=8 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=8 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x140001000" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "mov al, spl-less form: 0xe0 without REX is AH",
      .capstone = "mov al, ah (2)",
      .bytes = B(0x88, 0xe0), .nbytes = 2,
      .want = "op=mov len=2 opsize=1 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=1 reg=0 size=1 high8=1 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },

    /* ---- addressing and width rules -------------------------------------
     * Every ModRM/SIB shape, the whole 16-bit r/m table, the high byte
     * registers, and the operand/address-size defaults with 0x66 and 0x67
     * swapping them.  These rows are the sampled, capstone-checked residue of
     * the exhaustive sweeps in tools/dec32-oracle.py, which compare roughly
     * 1.0M encodings against capstone CS_MODE_32 field by field; this table is
     * what survives into `make unit`, where capstone is not available.
     *
     * The 64-bit rows at the end are the tripwires for the two places where a
     * 32-bit rule most easily leaks into long mode: mod=00 rm=101 must stay
     * RIP-relative (including under 0x67), and SIB index=100 must remain a
     * real r12 index when REX.X is set rather than "no index". */
    { .mode32 = 1, .rip = 0x1000ull, .note = "SIB base+index*8+disp32",
      .capstone = "mov eax, dword ptr [ecx + edi*8 + 0x12345678] (7)",
      .bytes = B(0x8b, 0x84, 0xf9, 0x78, 0x56, 0x34, 0x12), .nbytes = 7,
      .want = "op=mov len=7 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=1 index=7 scale=3 riprel=0 disp=305419896 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "SIB base+index*2+disp8",
      .capstone = "mov eax, dword ptr [ebx + ecx*2 + 0x10] (4)",
      .bytes = B(0x8b, 0x44, 0x4b, 0x10), .nbytes = 4,
      .want = "op=mov len=4 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=3 index=1 scale=1 riprel=0 disp=16 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "SIB base only, index=100 means NO index",
      .capstone = "mov eax, dword ptr [ebx] (3)",
      .bytes = B(0x8b, 0x04, 0x23), .nbytes = 3,
      .want = "op=mov len=3 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=3 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "SIB with esp as base",
      .capstone = "mov eax, dword ptr [esp] (3)",
      .bytes = B(0x8b, 0x04, 0x24), .nbytes = 3,
      .want = "op=mov len=3 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=4 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "SIB base=101 mod=00 is disp32 with no base",
      .capstone = "mov eax, dword ptr [0x12345678] (7)",
      .bytes = B(0x8b, 0x04, 0x25, 0x78, 0x56, 0x34, 0x12), .nbytes = 7,
      .want = "op=mov len=7 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=305419896 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "SIB base=101 mod=01 IS ebp+disp8",
      .capstone = "mov eax, dword ptr [ebp + 0x10] (4)",
      .bytes = B(0x8b, 0x44, 0x25, 0x10), .nbytes = 4,
      .want = "op=mov len=4 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=5 index=255 scale=0 riprel=0 disp=16 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "SIB base=101 mod=10 IS ebp+disp32",
      .capstone = "mov eax, dword ptr [ebp + 0x12345678] (7)",
      .bytes = B(0x8b, 0x84, 0x25, 0x78, 0x56, 0x34, 0x12), .nbytes = 7,
      .want = "op=mov len=7 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=5 index=255 scale=0 riprel=0 disp=305419896 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "SIB index*1 (scale 0)",
      .capstone = "mov eax, dword ptr [eax + edi] (3)",
      .bytes = B(0x8b, 0x04, 0x38), .nbytes = 3,
      .want = "op=mov len=3 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=0 index=7 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "absolute disp32 with the high bit set",
      .capstone = "mov ecx, dword ptr [0xffffffff] (6)",
      .bytes = B(0x8b, 0x0d, 0xff, 0xff, 0xff, 0xff), .nbytes = 6,
      .want = "op=mov len=6 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=1 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=-1 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "gs override on an absolute",
      .capstone = "mov ecx, dword ptr gs:[0] (7)",
      .bytes = B(0x65, 0x8b, 0x0d, 0x00, 0x00, 0x00, 0x00), .nbytes = 7,
      .want = "op=mov len=7 opsize=4 addrsize=4 seg=2 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=1 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "ds override folds to SEG_NONE (flat)",
      .capstone = "mov eax, dword ptr ds:[eax] (3)",
      .bytes = B(0x3e, 0x8b, 0x00), .nbytes = 3,
      .want = "op=mov len=3 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=0 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "lea with a full SIB",
      .capstone = "lea ecx, [eax + edx*4 + 4] (7)",
      .bytes = B(0x8d, 0x8c, 0x90, 0x04, 0x00, 0x00, 0x00), .nbytes = 7,
      .want = "op=lea len=7 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=1 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=0 index=2 scale=2 riprel=0 disp=4 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "addr16 [bx+si]",
      .capstone = "mov eax, dword ptr [bx + si] (3)",
      .bytes = B(0x67, 0x8b, 0x00), .nbytes = 3,
      .want = "op=mov len=3 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=3 index=6 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "addr16 [bx+di]",
      .capstone = "mov eax, dword ptr [bx + di] (3)",
      .bytes = B(0x67, 0x8b, 0x01), .nbytes = 3,
      .want = "op=mov len=3 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=3 index=7 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "addr16 [bp+si]",
      .capstone = "mov eax, dword ptr [bp + si] (3)",
      .bytes = B(0x67, 0x8b, 0x02), .nbytes = 3,
      .want = "op=mov len=3 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=5 index=6 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "addr16 [bp+di]",
      .capstone = "mov eax, dword ptr [bp + di] (3)",
      .bytes = B(0x67, 0x8b, 0x03), .nbytes = 3,
      .want = "op=mov len=3 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=5 index=7 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "addr16 [si]",
      .capstone = "mov eax, dword ptr [si] (3)",
      .bytes = B(0x67, 0x8b, 0x04), .nbytes = 3,
      .want = "op=mov len=3 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=6 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "addr16 [di]",
      .capstone = "mov eax, dword ptr [di] (3)",
      .bytes = B(0x67, 0x8b, 0x05), .nbytes = 3,
      .want = "op=mov len=3 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=7 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "addr16 disp16 at mod=00 rm=110",
      .capstone = "mov eax, dword ptr [0x1234] (5)",
      .bytes = B(0x67, 0x8b, 0x06, 0x34, 0x12), .nbytes = 5,
      .want = "op=mov len=5 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=4660 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "addr16 [bx]",
      .capstone = "mov eax, dword ptr [bx] (3)",
      .bytes = B(0x67, 0x8b, 0x07), .nbytes = 3,
      .want = "op=mov len=3 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=3 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "addr16 [bp+si+disp8]",
      .capstone = "mov eax, dword ptr [bp + si + 0x10] (4)",
      .bytes = B(0x67, 0x8b, 0x42, 0x10), .nbytes = 4,
      .want = "op=mov len=4 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=5 index=6 scale=0 riprel=0 disp=16 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "addr16 [bp+disp8] -- rm=110 with mod!=0 IS bp",
      .capstone = "mov eax, dword ptr [bp + 0x10] (4)",
      .bytes = B(0x67, 0x8b, 0x46, 0x10), .nbytes = 4,
      .want = "op=mov len=4 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=5 index=255 scale=0 riprel=0 disp=16 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "addr16 [bx+disp16]",
      .capstone = "mov eax, dword ptr [bx + 0x1000] (5)",
      .bytes = B(0x67, 0x8b, 0x87, 0x00, 0x10), .nbytes = 5,
      .want = "op=mov len=5 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=3 index=255 scale=0 riprel=0 disp=4096 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "addr16 rm=100 is [si], NOT a SIB byte",
      .capstone = "mov esp, dword ptr [si] (3)",
      .bytes = B(0x67, 0x8b, 0x24), .nbytes = 3,
      .want = "op=mov len=3 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=4 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=6 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "addr16 negative disp8 sign-extends",
      .capstone = "mov eax, dword ptr [bx - 4] (4)",
      .bytes = B(0x67, 0x8b, 0x47, 0xfc), .nbytes = 4,
      .want = "op=mov len=4 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=3 index=255 scale=0 riprel=0 disp=-4 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "addr16 + 0x66: 16-bit operand and 16-bit address",
      .capstone = "mov ax, word ptr [bx] (4)",
      .bytes = B(0x66, 0x67, 0x8b, 0x07), .nbytes = 4,
      .want = "op=mov len=4 opsize=2 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=2 high8=0 base=3 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "addr16 mod=11 is still a plain register",
      .capstone = "mov eax, ecx (3)",
      .bytes = B(0x67, 0x8b, 0xc1), .nbytes = 3,
      .want = "op=mov len=3 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=1 reg=1 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "mov ch, dh -- both high bytes",
      .capstone = "mov ch, dh (2)",
      .bytes = B(0x88, 0xf5), .nbytes = 2,
      .want = "op=mov len=2 opsize=1 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=1 size=1 high8=1 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=1 reg=2 size=1 high8=1 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "mov bh, bl",
      .capstone = "mov bh, bl (2)",
      .bytes = B(0x88, 0xdf), .nbytes = 2,
      .want = "op=mov len=2 opsize=1 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=3 size=1 high8=1 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=1 reg=3 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "xor bh, bh",
      .capstone = "xor bh, bh (2)",
      .bytes = B(0x30, 0xff), .nbytes = 2,
      .want = "op=xor len=2 opsize=1 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=3 size=1 high8=1 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=1 reg=3 size=1 high8=1 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "movzx eax, ah",
      .capstone = "movzx eax, ah (3)",
      .bytes = B(0x0f, 0xb6, 0xc4), .nbytes = 3,
      .want = "op=movzx len=3 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=1 reg=0 size=1 high8=1 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "movsx eax, bh",
      .capstone = "movsx eax, bh (3)",
      .bytes = B(0x0f, 0xbe, 0xc7), .nbytes = 3,
      .want = "op=movsx len=3 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=1 reg=3 size=1 high8=1 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "sete dh",
      .capstone = "sete dh (3)",
      .bytes = B(0x0f, 0x94, 0xc6), .nbytes = 3,
      .want = "op=setcc len=3 opsize=1 addrsize=4 seg=0 rep=0 lock=0 cc=4 nops=1 | op0 kind=1 reg=2 size=1 high8=1 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "inc dh via FE /0",
      .capstone = "inc dh (2)",
      .bytes = B(0xfe, 0xc6), .nbytes = 2,
      .want = "op=inc len=2 opsize=1 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=1 reg=2 size=1 high8=1 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "cmp ah, imm8",
      .capstone = "cmp ah, 5 (3)",
      .bytes = B(0x80, 0xfc, 0x05), .nbytes = 3,
      .want = "op=cmp len=3 opsize=1 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=1 high8=1 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=5 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x5" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "mov bh, imm8",
      .capstone = "mov bh, 0x5a (2)",
      .bytes = B(0xb7, 0x5a), .nbytes = 2,
      .want = "op=mov len=2 opsize=1 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=3 size=1 high8=1 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=5 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x5a" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "test ah, al",
      .capstone = "test ah, al (2)",
      .bytes = B(0x84, 0xc4), .nbytes = 2,
      .want = "op=test len=2 opsize=1 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=1 high8=1 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=1 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "byte load into ah keeps the memory operand 1 byte",
      .capstone = "mov ah, byte ptr [0x402000] (6)",
      .bytes = B(0x8a, 0x25, 0x00, 0x20, 0x40, 0x00), .nbytes = 6,
      .want = "op=mov len=6 opsize=1 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=1 high8=1 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=4202496 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "0x66 shrinks the operand, address stays 32",
      .capstone = "mov ax, word ptr [eax] (3)",
      .bytes = B(0x66, 0x8b, 0x00), .nbytes = 3,
      .want = "op=mov len=3 opsize=2 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=2 high8=0 base=0 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "0x67 shrinks the address, operand stays 32",
      .capstone = "mov eax, dword ptr [bx] (3)",
      .bytes = B(0x67, 0x8b, 0x07), .nbytes = 3,
      .want = "op=mov len=3 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=3 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "0x66 and 0x67 together shrink both",
      .capstone = "mov ax, word ptr [bx] (4)",
      .bytes = B(0x66, 0x67, 0x8b, 0x07), .nbytes = 4,
      .want = "op=mov len=4 opsize=2 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=2 high8=0 base=3 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "0x67 does not touch an immediate",
      .capstone = "mov eax, 0x12345678 (6)",
      .bytes = B(0x67, 0xb8, 0x78, 0x56, 0x34, 0x12), .nbytes = 6,
      .want = "op=mov len=6 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=5 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x12345678" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "0x66 does shrink an immediate",
      .capstone = "mov ax, 0x1234 (4)",
      .bytes = B(0x66, 0xb8, 0x34, 0x12), .nbytes = 4,
      .want = "op=mov len=4 opsize=2 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=5 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x1234" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "0x66 shrinks mov r/m,imm too",
      .capstone = "mov word ptr [eax], 0x1234 (5)",
      .bytes = B(0x66, 0xc7, 0x00, 0x34, 0x12), .nbytes = 5,
      .want = "op=mov len=5 opsize=2 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=4 reg=0 size=2 high8=0 base=0 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=5 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x1234" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "xchg eax, edi",
      .capstone = "xchg edi, eax (1)",
      .bytes = B(0x97), .nbytes = 1,
      .want = "op=xchg len=1 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=1 reg=7 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "0x66 xchg ax, di",
      .capstone = "xchg di, ax (2)",
      .bytes = B(0x66, 0x97), .nbytes = 2,
      .want = "op=xchg len=2 opsize=2 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=1 reg=7 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "cwde",
      .capstone = "cwde (1)",
      .bytes = B(0x98), .nbytes = 1,
      .want = "op=cbw len=1 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "0x66 cbw",
      .capstone = "cbw (2)",
      .bytes = B(0x66, 0x98), .nbytes = 2,
      .want = "op=cbw len=2 opsize=2 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "sgdt writes a 6-byte pseudo-descriptor in 32-bit mode",
      .capstone = "sgdt [eax] (3)",
      .bytes = B(0x0f, 0x01, 0x00), .nbytes = 3,
      .want = "op=sgdt len=3 opsize=0 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=4 reg=0 size=6 high8=0 base=0 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "sidt likewise",
      .capstone = "sidt [eax] (3)",
      .bytes = B(0x0f, 0x01, 0x08), .nbytes = 3,
      .want = "op=sidt len=3 opsize=0 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=4 reg=0 size=6 high8=0 base=0 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "mod=00 rm=101 stays RIP-relative under 0x67",
      .capstone = "mov eax, dword ptr [eip + 0x4030201] (7)",
      .bytes = B(0x67, 0x8b, 0x05, 0x01, 0x02, 0x03, 0x04), .nbytes = 7,
      .want = "op=mov len=7 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=1 disp=5436019208 imm=0x0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "SIB index=100 with REX.X IS r12, not 'no index'",
      .capstone = "mov eax, dword ptr [rax + r12] (4)",
      .bytes = B(0x42, 0x8b, 0x04, 0x20), .nbytes = 4,
      .want = "op=mov len=4 opsize=4 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=0 index=12 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "SIB base=101 mod=00 is still disp32 with no base",
      .capstone = "mov eax, dword ptr [0x12345678] (7)",
      .bytes = B(0x8b, 0x04, 0x25, 0x78, 0x56, 0x34, 0x12), .nbytes = 7,
      .want = "op=mov len=7 opsize=4 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=305419896 imm=0x0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "0x67 selects 32-bit addressing, never 16-bit",
      .capstone = "mov eax, dword ptr [edi] (3)",
      .bytes = B(0x67, 0x8b, 0x07), .nbytes = 3,
      .want = "op=mov len=3 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=7 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "REX makes reg 4 SPL, not AH",
      .capstone = "mov al, spl (3)",
      .bytes = B(0x40, 0x88, 0xe0), .nbytes = 3,
      .want = "op=mov len=3 opsize=1 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=1 reg=4 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "no REX still means AH for reg 4",
      .capstone = "mov al, ah (2)",
      .bytes = B(0x88, 0xe0), .nbytes = 2,
      .want = "op=mov len=2 opsize=1 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=1 reg=0 size=1 high8=1 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "sgdt still writes 10 bytes in long mode",
      .capstone = "sgdt [rax] (3)",
      .bytes = B(0x0f, 0x01, 0x00), .nbytes = 3,
      .want = "op=sgdt len=3 opsize=0 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=4 reg=0 size=10 high8=0 base=0 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "sidt likewise",
      .capstone = "sidt [rax] (3)",
      .bytes = B(0x0f, 0x01, 0x08), .nbytes = 3,
      .want = "op=sidt len=3 opsize=0 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=4 reg=0 size=10 high8=0 base=0 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "0x40-0x4f are REX, so 0x47 is a prefix not INC",
      .capstone = "mov r8d, dword ptr [r8 + r12] (4)",
      .bytes = B(0x47, 0x8b, 0x04, 0x20), .nbytes = 4,
      .want = "op=mov len=4 opsize=4 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=8 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=8 index=12 scale=0 riprel=0 disp=0 imm=0x0" },
};

/* Fold a decoded instruction into the same canonical line the table holds. */
static void render(const X86Insn *ins, char *b, size_t cap)
{
    size_t n = (size_t)snprintf(b, cap,
        "op=%s len=%u opsize=%u addrsize=%u seg=%u rep=%u lock=%u cc=%u nops=%u",
        ocerz_op_name(ins->op), ins->len, ins->opsize, ins->addrsize,
        ins->seg, ins->rep, ins->lock, ins->cc, ins->nops);
    for (int i = 0; i < ins->nops && i < 3 && n < cap; i++) {
        const X86Operand *o = &ins->ops[i];
        n += (size_t)snprintf(b + n, cap - n,
            " | op%d kind=%u reg=%u size=%u high8=%u base=%u index=%u scale=%u"
            " riprel=%u disp=%lld imm=0x%llx",
            i, o->kind, o->reg, o->size, o->high8, o->base, o->index,
            o->scale, o->riprel, (long long)o->disp,
            (unsigned long long)o->imm);
    }
}

/* Pull the "(N)" size capstone printed out of the recorded string. */
static int capstone_len(const char *s)
{
    const char *p = strrchr(s, '(');
    return p ? atoi(p + 1) : -1;
}

static int run_case(const Case32 *c)
{
    X86Insn insn;
    char got[512];
    memset(&insn, 0, sizeof insn);
    int rc = ocerz_decode_mode(c->bytes, (size_t)c->nbytes, c->rip, &insn,
                               c->mode32);
    if (rc != OCERZ_OK) {
        printf("FAIL [%s] %s: decode returned %d\n",
               c->mode32 ? "32" : "64", c->note, rc);
        return 1;
    }
    if (insn.mode32 != (uint8_t)c->mode32) {
        printf("FAIL [%s] %s: insn.mode32 = %u\n",
               c->mode32 ? "32" : "64", c->note, insn.mode32);
        return 1;
    }
    int want_len = capstone_len(c->capstone);
    if (want_len != (int)insn.len) {
        printf("FAIL [%s] %s: len %u, capstone says %d (%s)\n",
               c->mode32 ? "32" : "64", c->note, insn.len, want_len,
               c->capstone);
        return 1;
    }
    render(&insn, got, sizeof got);
    if (strcmp(got, c->want) != 0) {
        printf("FAIL [%s] %s\n  capstone: %s\n  want: %s\n  got:  %s\n",
               c->mode32 ? "32" : "64", c->note, c->capstone, c->want, got);
        return 1;
    }
    return 0;
}

/* ocerz_decode() must be exactly ocerz_decode_mode(..., 0), for every input,
 * not just the sampled ones -- that identity is what keeps tools/decodiff (a
 * 64-bit-only sweep through ocerz_decode) an honest gate on the mode seam.
 * Sweeping all 2^16 two-byte openings with a fixed tail is cheap and covers
 * every prefix pair, every opcode, and every ModRM.  Whole-struct memcmp, so
 * a newly added X86Insn field cannot quietly diverge either. */
static int check_default_entry(void)
{
    static const uint8_t tail[14] = {
        0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77,
        0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd, 0xee,
    };
    uint8_t code[16];
    memcpy(code + 2, tail, sizeof tail);
    int fails = 0;
    for (unsigned i = 0; i < 0x10000u; i++) {
        code[0] = (uint8_t)i;
        code[1] = (uint8_t)(i >> 8);
        X86Insn a, b;
        memset(&a, 0, sizeof a);
        memset(&b, 0, sizeof b);
        int ra = ocerz_decode(code, sizeof code, 0x140001000ull, &a);
        int rb = ocerz_decode_mode(code, sizeof code, 0x140001000ull, &b, 0);
        if (ra != rb || memcmp(&a, &b, sizeof a) != 0) {
            printf("FAIL default entry: %02x %02x diverges from mode32=0\n",
                   code[0], code[1]);
            if (++fails > 4)
                break;
        } else if (ra == OCERZ_OK && a.mode32 != 0) {
            printf("FAIL default entry: %02x %02x reports mode32=%u\n",
                   code[0], code[1], a.mode32);
            if (++fails > 4)
                break;
        }
    }
    return fails;
}

int main(void)
{
    int n = (int)(sizeof cases / sizeof cases[0]);
    int fails = 0;
    for (int i = 0; i < n; i++)
        fails += run_case(&cases[i]);
    fails += check_default_entry();
    if (fails == 0) {
        printf("test_decode32_addr: all %d cases passed\n", n);
        return 0;
    }
    printf("test_decode32_addr: %d failures across %d cases\n", fails, n);
    return 1;
}
