/*
 * tests/unit/test_corpus.c
 *
 * Decoder length cross-validation against the host x86_64 toolchain.
 *
 * tests/corpus/corpus.inc is generated by tools/gen_corpus.sh from the real
 * Apple/LLVM x86_64 assembler: every row is X("mnemonic", LEN, byte, byte...)
 * carrying an instruction's exact encoded bytes and its ground-truth length.
 * This test defines the X macro to build a table of those rows, then runs
 * ocerz_decode on each byte string and checks two things:
 *   (a) decode succeeds (returns OCERZ_OK), and
 *   (b) the decoded length out.len equals the toolchain's LEN.
 *
 * Length agreement is the property that matters most for a streaming decoder:
 * a single off-by-one desync misaligns every subsequent instruction in a
 * basic block, so a length bug anywhere on the ISA surface is caught here
 * rather than as mysterious downstream garbage. The corpus spans every
 * instruction family the decoder enum claims (ALU operand templates, all
 * addressing-mode shapes incl. the r12/r13/rbp SIB-and-disp special cases,
 * 8-bit high/low registers, fs/gs and 67h prefixes, the REX permutation set,
 * the movzx/movsx/movslq matrix, shifts/rotates, the branch family, string
 * ops with rep prefixes, push/pop, a representative x87 set, the full
 * SSE/SSE2 list plus SSSE3/SSE4.1, atomics, and the misc/system group).
 *
 * Each corpus byte string is decoded with the full 15 bytes available made
 * up of the instruction bytes followed by zero padding, so the decoder never
 * sees a spurious truncation; rip is a fixed nonzero value so rip-relative
 * resolution exercises real arithmetic. On any mismatch the failing case is
 * printed (mnemonic, raw bytes, expected vs got status/length) and counted;
 * main returns the total failure count, so a clean run exits 0.
 *
 * The test depends only on include/ocerz/decode.h (the decoder contract) and
 * never on src/decode.c internals, which a separate agent owns; it compiles
 * cleanly as an object before any decoder implementation exists.
 */
#include "ocerz/decode.h"

#include <stdio.h>
#include <string.h>

typedef struct CorpusEntry {
    const char *mnem;
    unsigned len;
    unsigned char bytes[15];
    unsigned nbytes;
} CorpusEntry;

#define X(MNEM, LEN, ...) \
    { (MNEM), (LEN), { __VA_ARGS__ }, (unsigned)(sizeof((unsigned char[]){ __VA_ARGS__ })) },

static const CorpusEntry corpus[] = {
#include "../corpus/corpus.inc"
};

#undef X

#define CORPUS_COUNT ((int)(sizeof(corpus) / sizeof(corpus[0])))

static void hex_bytes(char *dst, size_t cap, const unsigned char *b, unsigned n)
{
    size_t pos = 0;
    for (unsigned i = 0; i < n && pos + 4 < cap; i++)
        pos += (size_t)snprintf(dst + pos, cap - pos, "%02x ", b[i]);
    if (pos > 0 && dst[pos - 1] == ' ')
        dst[pos - 1] = '\0';
    else if (cap > 0)
        dst[0] = '\0';
}

int main(void)
{
    int failures = 0;

    for (int i = 0; i < CORPUS_COUNT; i++) {
        const CorpusEntry *e = &corpus[i];
        unsigned char buf[15];
        char hexbuf[64];

        memset(buf, 0, sizeof buf);
        memcpy(buf, e->bytes, e->nbytes);

        X86Insn out;
        memset(&out, 0, sizeof out);

        int rc = ocerz_decode(buf, sizeof buf, 0x140000000ull, &out);

        if (rc != OCERZ_OK) {
            hex_bytes(hexbuf, sizeof hexbuf, e->bytes, e->nbytes);
            fprintf(stderr,
                    "FAIL %-24s [%s]: decode rc=%d (expected OCERZ_OK), len=%u\n",
                    e->mnem, hexbuf, rc, e->len);
            failures++;
            continue;
        }

        if (out.len != e->len) {
            hex_bytes(hexbuf, sizeof hexbuf, e->bytes, e->nbytes);
            fprintf(stderr,
                    "FAIL %-24s [%s]: len got=%u expected=%u\n",
                    e->mnem, hexbuf, (unsigned)out.len, e->len);
            failures++;
            continue;
        }
    }

    if (failures == 0)
        printf("test_corpus: OK (%d instructions)\n", CORPUS_COUNT);
    else
        fprintf(stderr, "test_corpus: %d/%d FAILED\n", failures, CORPUS_COUNT);

    return failures;
}
