/* Unit tests for the i386 (32-bit) decode path added by ocerz_decode_mode().
 *
 * Every row was generated by running the real capstone 5.0.7 disassembler as
 * an oracle and only accepting the row when capstone's instruction LENGTH
 * agreed with ours; capstone's own rendering is kept in each row so the
 * provenance is visible, and the length embedded in that string is re-checked
 * here at run time.  The test itself has no capstone dependency.
 *
 * The `want` string is the full canonical record -- every X86Insn and
 * X86Operand field the decoder fills in -- so any change to any of them shows
 * up as a failure rather than being silently checked-around.
 *
 * The 64-bit rows are not decoration: they pin the long-mode behaviour of
 * exactly the sites the mode seam threads through, so a future edit that
 * "helpfully" makes one of them mode-aware fails here as well as in decodiff.
 */
#include "ocerz/decode.h"
#include "ocerz/cpu.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct Case32 {
    int mode32;
    uint64_t rip;
    const char *note;
    const char *capstone;   /* verbatim capstone output, "mnem ops (size)" */
    uint8_t bytes[12];
    int nbytes;
    const char *want;
} Case32;

#define B(...) { __VA_ARGS__ }

static const Case32 cases[] = {
    { .mode32 = 1, .rip = 0x1000ull, .note = "mov eax, [0x18] -- the flat 32-bit moffs",
      .capstone = "mov eax, dword ptr [0x18] (5)",
      .bytes = B(0xa1, 0x18, 0x00, 0x00, 0x00), .nbytes = 5,
      .want = "op=mov len=5 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=24 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "mov eax, fs:[0x18] -- the TEB read",
      .capstone = "mov eax, dword ptr fs:[0x18] (6)",
      .bytes = B(0x64, 0xa1, 0x18, 0x00, 0x00, 0x00), .nbytes = 6,
      .want = "op=mov len=6 opsize=4 addrsize=4 seg=1 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=24 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "moffs shrinks to 16 bits under 0x67",
      .capstone = "mov eax, dword ptr [0x1234] (4)",
      .bytes = B(0x67, 0xa1, 0x34, 0x12), .nbytes = 4,
      .want = "op=mov len=4 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=4660 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "mod=00 rm=101 is absolute, NOT rip-relative",
      .capstone = "mov eax, dword ptr [0x12345678] (6)",
      .bytes = B(0x8b, 0x05, 0x78, 0x56, 0x34, 0x12), .nbytes = 6,
      .want = "op=mov len=6 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=305419896 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "[ebp+disp8]",
      .capstone = "mov eax, dword ptr [ebp + 8] (3)",
      .bytes = B(0x8b, 0x45, 0x08), .nbytes = 3,
      .want = "op=mov len=3 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=5 index=255 scale=0 riprel=0 disp=8 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "SIB with no base",
      .capstone = "mov eax, dword ptr [ecx*4 + 0x12345678] (7)",
      .bytes = B(0x8b, 0x04, 0x8d, 0x78, 0x56, 0x34, 0x12), .nbytes = 7,
      .want = "op=mov len=7 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=255 index=1 scale=2 riprel=0 disp=305419896 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "jmp dword [eax] -- near branch is 4 bytes wide",
      .capstone = "jmp dword ptr [eax] (2)",
      .bytes = B(0xff, 0x20), .nbytes = 2,
      .want = "op=jmp len=2 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=4 reg=0 size=4 high8=0 base=0 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "jmp eax",
      .capstone = "jmp eax (2)",
      .bytes = B(0xff, 0xe0), .nbytes = 2,
      .want = "op=jmp len=2 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "jmp ax -- 0x66 DOES apply to near branches in 32-bit",
      .capstone = "jmp ax (3)",
      .bytes = B(0x66, 0xff, 0xe0), .nbytes = 3,
      .want = "op=jmp len=3 opsize=2 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=1 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "call eax",
      .capstone = "call eax (2)",
      .bytes = B(0xff, 0xd0), .nbytes = 2,
      .want = "op=call len=2 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "call dword [abs]",
      .capstone = "call dword ptr [0x12345678] (6)",
      .bytes = B(0xff, 0x15, 0x78, 0x56, 0x34, 0x12), .nbytes = 6,
      .want = "op=call len=6 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=4 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=305419896 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "push eax -- 4-byte stack slot",
      .capstone = "push eax (1)",
      .bytes = B(0x50), .nbytes = 1,
      .want = "op=push len=1 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "push ax",
      .capstone = "push ax (2)",
      .bytes = B(0x66, 0x50), .nbytes = 2,
      .want = "op=push len=2 opsize=2 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=1 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "pop eax",
      .capstone = "pop eax (1)",
      .bytes = B(0x58), .nbytes = 1,
      .want = "op=pop len=1 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "push imm32",
      .capstone = "push 0x12345678 (5)",
      .bytes = B(0x68, 0x78, 0x56, 0x34, 0x12), .nbytes = 5,
      .want = "op=push len=5 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x12345678" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "push imm8",
      .capstone = "push 0x7f (2)",
      .bytes = B(0x6a, 0x7f), .nbytes = 2,
      .want = "op=push len=2 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x7f" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "push dword [eax]",
      .capstone = "push dword ptr [eax] (2)",
      .bytes = B(0xff, 0x30), .nbytes = 2,
      .want = "op=push len=2 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=4 reg=0 size=4 high8=0 base=0 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "pop dword [eax]",
      .capstone = "pop dword ptr [eax] (2)",
      .bytes = B(0x8f, 0x00), .nbytes = 2,
      .want = "op=pop len=2 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=4 reg=0 size=4 high8=0 base=0 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "ret",
      .capstone = "ret (1)",
      .bytes = B(0xc3), .nbytes = 1,
      .want = "op=ret len=1 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "ret 8",
      .capstone = "ret 8 (3)",
      .bytes = B(0xc2, 0x08, 0x00), .nbytes = 3,
      .want = "op=ret len=3 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x8" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "leave",
      .capstone = "leave (1)",
      .bytes = B(0xc9), .nbytes = 1,
      .want = "op=leave len=1 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "pushfd",
      .capstone = "pushfd (1)",
      .bytes = B(0x9c), .nbytes = 1,
      .want = "op=pushf len=1 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "popfd",
      .capstone = "popfd (1)",
      .bytes = B(0x9d), .nbytes = 1,
      .want = "op=popf len=1 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "jmp rel32",
      .capstone = "jmp 0x1234667d (5)",
      .bytes = B(0xe9, 0x78, 0x56, 0x34, 0x12), .nbytes = 5,
      .want = "op=jmp len=5 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x1234667d" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "jmp rel16 -- 0x66 shortens the displacement",
      .capstone = "jmp 0x2238 (4)",
      .bytes = B(0x66, 0xe9, 0x34, 0x12), .nbytes = 4,
      .want = "op=jmp len=4 opsize=2 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x2238" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "call rel32",
      .capstone = "call 0x1234667d (5)",
      .bytes = B(0xe8, 0x78, 0x56, 0x34, 0x12), .nbytes = 5,
      .want = "op=call len=5 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x1234667d" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "jmp rel8",
      .capstone = "jmp 0x1007 (2)",
      .bytes = B(0xeb, 0x05), .nbytes = 2,
      .want = "op=jmp len=2 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x1007" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "je rel8",
      .capstone = "je 0x1007 (2)",
      .bytes = B(0x74, 0x05), .nbytes = 2,
      .want = "op=jcc len=2 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=4 nops=1 | op0 kind=5 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x1007" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "je rel32",
      .capstone = "je 0x1234667e (6)",
      .bytes = B(0x0f, 0x84, 0x78, 0x56, 0x34, 0x12), .nbytes = 6,
      .want = "op=jcc len=6 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=4 nops=1 | op0 kind=5 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x1234667e" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "je rel16",
      .capstone = "je 0x2239 (5)",
      .bytes = B(0x66, 0x0f, 0x84, 0x34, 0x12), .nbytes = 5,
      .want = "op=jcc len=5 opsize=2 addrsize=4 seg=0 rep=0 lock=0 cc=4 nops=1 | op0 kind=5 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x2239" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "jecxz",
      .capstone = "jecxz 0x1000 (2)",
      .bytes = B(0xe3, 0xfe), .nbytes = 2,
      .want = "op=jrcxz len=2 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x1000" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "mov al, ah -- AH exists only in 32-bit mode",
      .capstone = "mov al, ah (2)",
      .bytes = B(0x88, 0xe0), .nbytes = 2,
      .want = "op=mov len=2 opsize=1 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=1 reg=0 size=1 high8=1 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "mov ah, al",
      .capstone = "mov ah, al (2)",
      .bytes = B(0x8a, 0xe0), .nbytes = 2,
      .want = "op=mov len=2 opsize=1 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=1 high8=1 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=1 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "mov ah, imm8",
      .capstone = "mov ah, 0x12 (2)",
      .bytes = B(0xb4, 0x12), .nbytes = 2,
      .want = "op=mov len=2 opsize=1 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=1 high8=1 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=5 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x12" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "mov eax, imm32",
      .capstone = "mov eax, 0x12345678 (5)",
      .bytes = B(0xb8, 0x78, 0x56, 0x34, 0x12), .nbytes = 5,
      .want = "op=mov len=5 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=5 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x12345678" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "mov ax, imm16",
      .capstone = "mov ax, 0x1234 (4)",
      .bytes = B(0x66, 0xb8, 0x34, 0x12), .nbytes = 4,
      .want = "op=mov len=4 opsize=2 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=5 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x1234" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "add eax, 1",
      .capstone = "add eax, 1 (3)",
      .bytes = B(0x83, 0xc0, 0x01), .nbytes = 3,
      .want = "op=add len=3 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=5 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x1" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "mov dword [ebp-4], 1",
      .capstone = "mov dword ptr [ebp - 4], 1 (7)",
      .bytes = B(0xc7, 0x45, 0xfc, 0x01, 0x00, 0x00, 0x00), .nbytes = 7,
      .want = "op=mov len=7 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=4 reg=0 size=4 high8=0 base=5 index=255 scale=0 riprel=0 disp=-4 imm=0x0 | op1 kind=5 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x1" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "16-bit addressing: displacement-only at mod=00 rm=110",
      .capstone = "mov eax, dword ptr [0x1234] (5)",
      .bytes = B(0x67, 0x8b, 0x06, 0x34, 0x12), .nbytes = 5,
      .want = "op=mov len=5 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=4660 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "16-bit addressing: [bx+si]",
      .capstone = "mov eax, dword ptr [bx + si] (3)",
      .bytes = B(0x67, 0x8b, 0x00), .nbytes = 3,
      .want = "op=mov len=3 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=3 index=6 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "16-bit addressing: [bx+di+disp8]",
      .capstone = "mov eax, dword ptr [bx + di + 0x10] (4)",
      .bytes = B(0x67, 0x8b, 0x41, 0x10), .nbytes = 4,
      .want = "op=mov len=4 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=3 index=7 scale=0 riprel=0 disp=16 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "16-bit addressing: [bp+disp16]",
      .capstone = "mov eax, dword ptr [bp + 0x1234] (5)",
      .bytes = B(0x67, 0x8b, 0x86, 0x34, 0x12), .nbytes = 5,
      .want = "op=mov len=5 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=5 index=255 scale=0 riprel=0 disp=4660 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "16-bit addressing: [bx]",
      .capstone = "mov eax, dword ptr [bx] (3)",
      .bytes = B(0x67, 0x8b, 0x07), .nbytes = 3,
      .want = "op=mov len=3 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=3 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "16-bit addressing with a 16-bit operand",
      .capstone = "mov ax, word ptr [bx] (4)",
      .bytes = B(0x67, 0x66, 0x8b, 0x07), .nbytes = 4,
      .want = "op=mov len=4 opsize=2 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=2 high8=0 base=3 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "16-bit addressing: [si+disp8]",
      .capstone = "mov ebx, dword ptr [si + 8] (4)",
      .bytes = B(0x67, 0x8b, 0x5c, 0x08), .nbytes = 4,
      .want = "op=mov len=4 opsize=4 addrsize=2 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=3 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=6 index=255 scale=0 riprel=0 disp=8 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "rep movsd",
      .capstone = "rep movsd dword ptr es:[edi], dword ptr [esi] (2)",
      .bytes = B(0xf3, 0xa5), .nbytes = 2,
      .want = "op=movs len=2 opsize=4 addrsize=4 seg=0 rep=1 lock=0 cc=0 nops=0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "0x40 is REX here, not INC eax",
      .capstone = "nop (2)",
      .bytes = B(0x40, 0x90), .nbytes = 2,
      .want = "op=nop len=2 opsize=0 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "add rax, rbx",
      .capstone = "add rax, rbx (3)",
      .bytes = B(0x48, 0x01, 0xd8), .nbytes = 3,
      .want = "op=add len=3 opsize=8 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=8 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=1 reg=3 size=8 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "moffs follows the 32-bit address size",
      .capstone = "mov eax, dword ptr [0x4030201] (6)",
      .bytes = B(0x67, 0xa1, 0x01, 0x02, 0x03, 0x04), .nbytes = 6,
      .want = "op=mov len=6 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=67305985 imm=0x0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "moffs64",
      .capstone = "movabs eax, dword ptr [0x807060504030201] (9)",
      .bytes = B(0xa1, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08), .nbytes = 9,
      .want = "op=mov len=9 opsize=4 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=578437695752307201 imm=0x0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "mod=00 rm=101 IS rip-relative here",
      .capstone = "mov eax, dword ptr [rip + 0x12345678] (6)",
      .bytes = B(0x8b, 0x05, 0x78, 0x56, 0x34, 0x12), .nbytes = 6,
      .want = "op=mov len=6 opsize=4 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=1 disp=5674133118 imm=0x0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "jmp qword [rax] -- forced to 64 bits",
      .capstone = "jmp qword ptr [rax] (2)",
      .bytes = B(0xff, 0x20), .nbytes = 2,
      .want = "op=jmp len=2 opsize=8 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=4 reg=0 size=8 high8=0 base=0 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "0x66 is IGNORED on a near branch in 64-bit mode",
      .capstone = "jmp rax (3)",
      .bytes = B(0x66, 0xff, 0xe0), .nbytes = 3,
      .want = "op=jmp len=3 opsize=8 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=1 reg=0 size=8 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "push rax -- 8-byte stack slot",
      .capstone = "push rax (1)",
      .bytes = B(0x50), .nbytes = 1,
      .want = "op=push len=1 opsize=8 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=1 reg=0 size=8 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "push ax",
      .capstone = "push ax (2)",
      .bytes = B(0x66, 0x50), .nbytes = 2,
      .want = "op=push len=2 opsize=2 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=1 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "push imm8, 8-byte slot",
      .capstone = "push 0x7f (2)",
      .bytes = B(0x6a, 0x7f), .nbytes = 2,
      .want = "op=push len=2 opsize=8 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=8 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x7f" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "ret",
      .capstone = "ret (1)",
      .bytes = B(0xc3), .nbytes = 1,
      .want = "op=ret len=1 opsize=8 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "0x66 ret: HEAD reports the 8-byte form, pinned here",
      .capstone = "ret (2)",
      .bytes = B(0x66, 0xc3), .nbytes = 2,
      .want = "op=ret len=2 opsize=8 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "leave",
      .capstone = "leave (1)",
      .bytes = B(0xc9), .nbytes = 1,
      .want = "op=leave len=1 opsize=8 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "pushfq",
      .capstone = "pushfq (1)",
      .bytes = B(0x9c), .nbytes = 1,
      .want = "op=pushf len=1 opsize=8 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "jmp rel32 -- 0x66 does not shorten it",
      .capstone = "jmp 0x14000223a (6)",
      .bytes = B(0x66, 0xe9, 0x34, 0x12, 0x00, 0x00), .nbytes = 6,
      .want = "op=jmp len=6 opsize=8 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=8 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x14000223a" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "jrcxz",
      .capstone = "jrcxz 0x140001000 (2)",
      .bytes = B(0xe3, 0xfe), .nbytes = 2,
      .want = "op=jrcxz len=2 opsize=8 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=8 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x140001000" },
    { .mode32 = 0, .rip = 0x140001000ull, .note = "mov al, spl-less form: 0xe0 without REX is AH",
      .capstone = "mov al, ah (2)",
      .bytes = B(0x88, 0xe0), .nbytes = 2,
      .want = "op=mov len=2 opsize=1 addrsize=8 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=1 reg=0 size=1 high8=1 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },

    /* ---- stage 4a: the i386-only one-byte opcode map -------------------
     * Every row below was produced by decoding with ocerz and then REJECTED
     * unless capstone 5.0.7 in CS_MODE_32 agreed on the instruction length;
     * capstone's own rendering is kept verbatim so the provenance is visible
     * and the length in it is re-checked at run time.
     *
     * Two fields deliberately differ from what capstone reports, both because
     * capstone is not modelling the operand rather than because it disagrees:
     *   - LES/LDS memory size.  capstone reports 4 for both the 32- and the
     *     16-bit form and prints no size keyword; the SDM width of m16:32 is
     *     6 and of m16:16 is 4, which is what is recorded here.
     *   - PUSH/POP sreg.  There is no OCERZ_OPK_SREG in this decoder, so the
     *     segment is an OCERZ_OPK_IMM holding the sreg INDEX, exactly the
     *     convention OCERZ_OP_MOVSEG (0x8e) already uses.  insn.opsize carries
     *     the stack slot width, which is the field capstone's "sz2" is not.
     */
    { .mode32 = 1, .rip = 0x1000ull, .note = "inc eax",
      .capstone = "inc eax (1)",
      .bytes = B(0x40), .nbytes = 1,
      .want = "op=inc len=1 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "inc edi",
      .capstone = "inc edi (1)",
      .bytes = B(0x47), .nbytes = 1,
      .want = "op=inc len=1 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=1 reg=7 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "dec eax",
      .capstone = "dec eax (1)",
      .bytes = B(0x48), .nbytes = 1,
      .want = "op=dec len=1 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "dec edi",
      .capstone = "dec edi (1)",
      .bytes = B(0x4f), .nbytes = 1,
      .want = "op=dec len=1 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=1 reg=7 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "0x66 narrows inc/dec to 16 bits",
      .capstone = "inc ax (2)",
      .bytes = B(0x66, 0x40), .nbytes = 2,
      .want = "op=inc len=2 opsize=2 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=1 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "pushal",
      .capstone = "pushal (1)",
      .bytes = B(0x60), .nbytes = 1,
      .want = "op=pusha len=1 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "popal",
      .capstone = "popal (1)",
      .bytes = B(0x61), .nbytes = 1,
      .want = "op=popa len=1 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "pushaw under 0x66",
      .capstone = "pushaw (2)",
      .bytes = B(0x66, 0x60), .nbytes = 2,
      .want = "op=pusha len=2 opsize=2 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "popaw under 0x66",
      .capstone = "popaw (2)",
      .bytes = B(0x66, 0x61), .nbytes = 2,
      .want = "op=popa len=2 opsize=2 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "push es",
      .capstone = "push es (1)",
      .bytes = B(0x06), .nbytes = 1,
      .want = "op=push_sreg len=1 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "pop es",
      .capstone = "pop es (1)",
      .bytes = B(0x07), .nbytes = 1,
      .want = "op=pop_sreg len=1 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "push cs -- 0x0f is the escape, so the map has no pop cs",
      .capstone = "push cs (1)",
      .bytes = B(0x0e), .nbytes = 1,
      .want = "op=push_sreg len=1 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x1" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "push ss",
      .capstone = "push ss (1)",
      .bytes = B(0x16), .nbytes = 1,
      .want = "op=push_sreg len=1 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x2" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "pop ss",
      .capstone = "pop ss (1)",
      .bytes = B(0x17), .nbytes = 1,
      .want = "op=pop_sreg len=1 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x2" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "push ds",
      .capstone = "push ds (1)",
      .bytes = B(0x1e), .nbytes = 1,
      .want = "op=push_sreg len=1 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x3" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "pop ds",
      .capstone = "pop ds (1)",
      .bytes = B(0x1f), .nbytes = 1,
      .want = "op=pop_sreg len=1 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x3" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "push es with a 2-byte stack slot",
      .capstone = "push es (2)",
      .bytes = B(0x66, 0x06), .nbytes = 2,
      .want = "op=push_sreg len=2 opsize=2 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "daa",
      .capstone = "daa (1)",
      .bytes = B(0x27), .nbytes = 1,
      .want = "op=daa len=1 opsize=1 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "das",
      .capstone = "das (1)",
      .bytes = B(0x2f), .nbytes = 1,
      .want = "op=das len=1 opsize=1 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "aaa",
      .capstone = "aaa (1)",
      .bytes = B(0x37), .nbytes = 1,
      .want = "op=aaa len=1 opsize=2 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "aas",
      .capstone = "aas (1)",
      .bytes = B(0x3f), .nbytes = 1,
      .want = "op=aas len=1 opsize=2 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "bound eax, [ebp+8] -- the bounds PAIR is 8 bytes wide",
      .capstone = "bound eax, qword ptr [ebp + 8] (3)",
      .bytes = B(0x62, 0x45, 0x08), .nbytes = 3,
      .want = "op=bound len=3 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=8 high8=0 base=5 index=255 scale=0 riprel=0 disp=8 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "bound ax, [eax] -- 0x66 halves register and pair alike",
      .capstone = "bound ax, dword ptr [eax] (3)",
      .bytes = B(0x66, 0x62, 0x00), .nbytes = 3,
      .want = "op=bound len=3 opsize=2 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=0 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "bound eax, [ecx+edx] via SIB",
      .capstone = "bound eax, qword ptr [ecx + edx] (3)",
      .bytes = B(0x62, 0x04, 0x11), .nbytes = 3,
      .want = "op=bound len=3 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=8 high8=0 base=1 index=2 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "0x82 is the imm8 alias of 0x80: add al, 5",
      .capstone = "add al, 5 (3)",
      .bytes = B(0x82, 0xc0, 0x05), .nbytes = 3,
      .want = "op=add len=3 opsize=1 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=5 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x5" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "0x82 sub al, 0xff -- imm8 sign-extends exactly as 0x80 does",
      .capstone = "sub al, 0xff (3)",
      .bytes = B(0x82, 0xe8, 0xff), .nbytes = 3,
      .want = "op=sub len=3 opsize=1 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=5 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0xffffffffffffffff" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "0x82 on an absolute byte memory operand",
      .capstone = "add byte ptr [0x4030201], 7 (7)",
      .bytes = B(0x82, 0x05, 0x01, 0x02, 0x03, 0x04, 0x07), .nbytes = 7,
      .want = "op=add len=7 opsize=1 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=4 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=67305985 imm=0x0 | op1 kind=5 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x7" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "lcall ptr16:32 -- selector in op0, offset in op1",
      .capstone = "lcall 0x6655, 0x44332211 (7)",
      .bytes = B(0x9a, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66), .nbytes = 7,
      .want = "op=callf len=7 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=5 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x6655 | op1 kind=5 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x44332211" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "lcall ptr16:16 under 0x66",
      .capstone = "lcall 0x4433, 0x2211 (6)",
      .bytes = B(0x66, 0x9a, 0x11, 0x22, 0x33, 0x44), .nbytes = 6,
      .want = "op=callf len=6 opsize=2 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=5 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x4433 | op1 kind=5 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x2211" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "les eax, m16:32 -- the far pointer is 6 bytes",
      .capstone = "les eax, ptr [ebp + 8] (3)",
      .bytes = B(0xc4, 0x45, 0x08), .nbytes = 3,
      .want = "op=les len=3 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=6 high8=0 base=5 index=255 scale=0 riprel=0 disp=8 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "lds eax, m16:32",
      .capstone = "lds eax, ptr [eax] (2)",
      .bytes = B(0xc5, 0x00), .nbytes = 2,
      .want = "op=lds len=2 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=6 high8=0 base=0 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "les ax, m16:16 under 0x66",
      .capstone = "les ax, ptr [eax] (3)",
      .bytes = B(0x66, 0xc4, 0x00), .nbytes = 3,
      .want = "op=les len=3 opsize=2 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=1 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x0 | op1 kind=4 reg=0 size=4 high8=0 base=0 index=255 scale=0 riprel=0 disp=0 imm=0x0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "into",
      .capstone = "into (1)",
      .bytes = B(0xce), .nbytes = 1,
      .want = "op=into len=1 opsize=0 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "aam 0xa",
      .capstone = "aam 0xa (2)",
      .bytes = B(0xd4, 0x0a), .nbytes = 2,
      .want = "op=aam len=2 opsize=2 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0xa" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "aad 0xa",
      .capstone = "aad 0xa (2)",
      .bytes = B(0xd5, 0x0a), .nbytes = 2,
      .want = "op=aad len=2 opsize=2 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0xa" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "aam with a non-default base",
      .capstone = "aam 7 (2)",
      .bytes = B(0xd4, 0x07), .nbytes = 2,
      .want = "op=aam len=2 opsize=2 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=1 | op0 kind=5 reg=0 size=1 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x7" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "salc",
      .capstone = "salc (1)",
      .bytes = B(0xd6), .nbytes = 1,
      .want = "op=salc len=1 opsize=1 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=0" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "ljmp ptr16:32",
      .capstone = "ljmp 0x6655:0x44332211 (7)",
      .bytes = B(0xea, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66), .nbytes = 7,
      .want = "op=jmpf len=7 opsize=4 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=5 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x6655 | op1 kind=5 reg=0 size=4 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x44332211" },
    { .mode32 = 1, .rip = 0x1000ull, .note = "ljmp ptr16:16 under 0x66",
      .capstone = "ljmp 0x4433:0x2211 (6)",
      .bytes = B(0x66, 0xea, 0x11, 0x22, 0x33, 0x44), .nbytes = 6,
      .want = "op=jmpf len=6 opsize=2 addrsize=4 seg=0 rep=0 lock=0 cc=0 nops=2 | op0 kind=5 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x4433 | op1 kind=5 reg=0 size=2 high8=0 base=255 index=255 scale=0 riprel=0 disp=0 imm=0x2211" },
};

/* Encodings that must NOT decode.  The 64-bit rows are the readable statement
 * of the stage-4a invariant -- every i386-only byte stays undefined in long
 * mode -- which tools/decodiff proves exhaustively; these rows exist so that a
 * regression names itself here instead of only showing up as a hash mismatch.
 *
 * The 32-bit rows are real architectural holes: BOUND, LES and LDS all require
 * a memory r/m, and a mod=11 encoding is undefined (for C4/C5 it is a VEX
 * prefix, which ocerz does not implement in EITHER mode). */
typedef struct Bad32 {
    int mode32;
    const char *note;
    uint8_t bytes[8];
    int nbytes;
} Bad32;

static const Bad32 bad_cases[] = {
    { 1, "bound with a register r/m",            B(0x62, 0xc0), 2 },
    { 1, "les with a register r/m is VEX, not les", B(0xc4, 0xc0), 2 },
    { 1, "lds with a register r/m is VEX, not lds", B(0xc5, 0xc0), 2 },

    { 0, "0x60 pusha stays undefined in long mode", B(0x60), 1 },
    { 0, "0x61 popa stays undefined",            B(0x61), 1 },
    { 0, "0x06 push es stays undefined",         B(0x06), 1 },
    { 0, "0x07 pop es stays undefined",          B(0x07), 1 },
    { 0, "0x0e push cs stays undefined",         B(0x0e), 1 },
    { 0, "0x16 push ss stays undefined",         B(0x16), 1 },
    { 0, "0x17 pop ss stays undefined",          B(0x17), 1 },
    { 0, "0x1e push ds stays undefined",         B(0x1e), 1 },
    { 0, "0x1f pop ds stays undefined",          B(0x1f), 1 },
    { 0, "0x27 daa stays undefined",             B(0x27), 1 },
    { 0, "0x2f das stays undefined",             B(0x2f), 1 },
    { 0, "0x37 aaa stays undefined",             B(0x37), 1 },
    { 0, "0x3f aas stays undefined",             B(0x3f), 1 },
    { 0, "0x62 bound stays undefined",           B(0x62, 0x45, 0x08), 3 },
    { 0, "0x82 alias stays undefined",           B(0x82, 0xc0, 0x05), 3 },
    { 0, "0x9a far call stays undefined",        B(0x9a, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66), 7 },
    { 0, "0xc4 les stays undefined",             B(0xc4, 0x45, 0x08), 3 },
    { 0, "0xc5 lds stays undefined",             B(0xc5, 0x00), 2 },
    { 0, "0xce into stays undefined",            B(0xce), 1 },
    { 0, "0xd4 aam stays undefined",             B(0xd4, 0x0a), 2 },
    { 0, "0xd5 aad stays undefined",             B(0xd5, 0x0a), 2 },
    { 0, "0xd6 salc stays undefined",            B(0xd6), 1 },
    { 0, "0xea far jmp stays undefined",         B(0xea, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66), 7 },
};

static int run_bad(const Bad32 *c)
{
    X86Insn insn;
    memset(&insn, 0, sizeof insn);
    int rc = ocerz_decode_mode(c->bytes, (size_t)c->nbytes, 0x1000ull, &insn,
                               c->mode32);
    if (rc == OCERZ_OK) {
        printf("FAIL [%s] %s: decoded as %s (len %u), expected undefined\n",
               c->mode32 ? "32" : "64", c->note, ocerz_op_name(insn.op),
               insn.len);
        return 1;
    }
    return 0;
}

/* 0x40-0x4f must still be REX in long mode -- this is the one byte range where
 * the i386 map collides with a 64-bit prefix, so it gets its own check on top
 * of the bad_cases table.  REX+0x90 is NOP only when REX.B is clear; with
 * REX.B set the register field becomes r8 and it is a real XCHG, which
 * capstone confirms ("40 90" -> nop, "41 90" -> xchg r8d, eax).  Both arms are
 * asserted so that neither a lost nor a spuriously-applied REX.B passes. */
static int check_rex_still_rex(void)
{
    int fails = 0;
    for (unsigned b = 0x40; b <= 0x4f; b++) {
        const uint8_t code[2] = { (uint8_t)b, 0x90 };
        int rex_b = (int)(b & 1);
        const char *want = rex_b ? "xchg" : "nop";
        X86Insn insn;
        memset(&insn, 0, sizeof insn);
        if (ocerz_decode_mode(code, sizeof code, 0x140001000ull, &insn, 0) != OCERZ_OK
            || insn.len != 2 || strcmp(ocerz_op_name(insn.op), want) != 0) {
            printf("FAIL 64-bit %02x 90: expected REX+%s\n", b, want);
            fails++;
            continue;
        }
        /* REX.W must still pick the 64-bit operand size. */
        unsigned want_size = (b & 8) ? 8 : 4;
        if (rex_b && (insn.opsize != want_size || insn.ops[1].reg != 8)) {
            printf("FAIL 64-bit %02x 90: opsize %u reg %u, expected %u/8\n",
                   b, insn.opsize, insn.ops[1].reg, want_size);
            fails++;
        }
    }

    /* And in 32-bit mode the same bytes are INC/DEC of one of the 8 GPRs. */
    for (unsigned b = 0x40; b <= 0x4f; b++) {
        const uint8_t code[2] = { (uint8_t)b, 0x90 };
        const char *want = (b < 0x48) ? "inc" : "dec";
        X86Insn insn;
        memset(&insn, 0, sizeof insn);
        if (ocerz_decode_mode(code, sizeof code, 0x1000ull, &insn, 1) != OCERZ_OK
            || insn.len != 1 || strcmp(ocerz_op_name(insn.op), want) != 0
            || insn.ops[0].reg != (b & 7) || insn.ops[0].size != 4) {
            printf("FAIL 32-bit %02x: expected 1-byte %s of reg %u\n",
                   b, want, b & 7);
            fails++;
        }
    }
    return fails;
}

/* 0x82 is an ALIAS of 0x80, not a lookalike: for every ModRM and every
 * immediate the two must produce byte-identical X86Insn records.  Checking the
 * whole 16-bit (modrm, imm) space is cheap and rules out any drift between the
 * two entry points into group1(). */
static int check_82_aliases_80(void)
{
    int fails = 0;
    for (unsigned modrm = 0; modrm < 256; modrm++) {
        for (unsigned imm = 0; imm < 256; imm += 17) {
            uint8_t a[8] = { 0x80, (uint8_t)modrm, 0x01, 0x02, 0x03, 0x04, (uint8_t)imm, 0 };
            uint8_t b[8] = { 0x82, (uint8_t)modrm, 0x01, 0x02, 0x03, 0x04, (uint8_t)imm, 0 };
            X86Insn ia, ib;
            memset(&ia, 0, sizeof ia);
            memset(&ib, 0, sizeof ib);
            int ra = ocerz_decode_mode(a, sizeof a, 0x1000ull, &ia, 1);
            int rb = ocerz_decode_mode(b, sizeof b, 0x1000ull, &ib, 1);
            if (ra != rb) {
                printf("FAIL 0x82 alias: modrm %02x rc %d vs %d\n", modrm, ra, rb);
                if (++fails > 4)
                    return fails;
                continue;
            }
            if (ra != OCERZ_OK)
                continue;
            /* Only the opcode byte differs, so every field including len must
             * match; ops[] is compared wholesale. */
            if (ia.op != ib.op || ia.len != ib.len || ia.opsize != ib.opsize ||
                ia.nops != ib.nops ||
                memcmp(ia.ops, ib.ops, sizeof ia.ops) != 0) {
                printf("FAIL 0x82 alias diverges from 0x80 at modrm %02x imm %02x\n",
                       modrm, imm);
                if (++fails > 4)
                    return fails;
            }
        }
    }
    return fails;
}

/* Fold a decoded instruction into the same canonical line the table holds. */
static void render(const X86Insn *ins, char *b, size_t cap)
{
    size_t n = (size_t)snprintf(b, cap,
        "op=%s len=%u opsize=%u addrsize=%u seg=%u rep=%u lock=%u cc=%u nops=%u",
        ocerz_op_name(ins->op), ins->len, ins->opsize, ins->addrsize,
        ins->seg, ins->rep, ins->lock, ins->cc, ins->nops);
    for (int i = 0; i < ins->nops && i < 3 && n < cap; i++) {
        const X86Operand *o = &ins->ops[i];
        n += (size_t)snprintf(b + n, cap - n,
            " | op%d kind=%u reg=%u size=%u high8=%u base=%u index=%u scale=%u"
            " riprel=%u disp=%lld imm=0x%llx",
            i, o->kind, o->reg, o->size, o->high8, o->base, o->index,
            o->scale, o->riprel, (long long)o->disp,
            (unsigned long long)o->imm);
    }
}

/* Pull the "(N)" size capstone printed out of the recorded string. */
static int capstone_len(const char *s)
{
    const char *p = strrchr(s, '(');
    return p ? atoi(p + 1) : -1;
}

static int run_case(const Case32 *c)
{
    X86Insn insn;
    char got[512];
    memset(&insn, 0, sizeof insn);
    int rc = ocerz_decode_mode(c->bytes, (size_t)c->nbytes, c->rip, &insn,
                               c->mode32);
    if (rc != OCERZ_OK) {
        printf("FAIL [%s] %s: decode returned %d\n",
               c->mode32 ? "32" : "64", c->note, rc);
        return 1;
    }
    if (insn.mode32 != (uint8_t)c->mode32) {
        printf("FAIL [%s] %s: insn.mode32 = %u\n",
               c->mode32 ? "32" : "64", c->note, insn.mode32);
        return 1;
    }
    int want_len = capstone_len(c->capstone);
    if (want_len != (int)insn.len) {
        printf("FAIL [%s] %s: len %u, capstone says %d (%s)\n",
               c->mode32 ? "32" : "64", c->note, insn.len, want_len,
               c->capstone);
        return 1;
    }
    render(&insn, got, sizeof got);
    if (strcmp(got, c->want) != 0) {
        printf("FAIL [%s] %s\n  capstone: %s\n  want: %s\n  got:  %s\n",
               c->mode32 ? "32" : "64", c->note, c->capstone, c->want, got);
        return 1;
    }
    return 0;
}

/* ocerz_decode() must be exactly ocerz_decode_mode(..., 0), for every input,
 * not just the sampled ones -- that identity is what keeps tools/decodiff (a
 * 64-bit-only sweep through ocerz_decode) an honest gate on the mode seam.
 * Sweeping all 2^16 two-byte openings with a fixed tail is cheap and covers
 * every prefix pair, every opcode, and every ModRM.  Whole-struct memcmp, so
 * a newly added X86Insn field cannot quietly diverge either. */
static int check_default_entry(void)
{
    static const uint8_t tail[14] = {
        0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77,
        0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd, 0xee,
    };
    uint8_t code[16];
    memcpy(code + 2, tail, sizeof tail);
    int fails = 0;
    for (unsigned i = 0; i < 0x10000u; i++) {
        code[0] = (uint8_t)i;
        code[1] = (uint8_t)(i >> 8);
        X86Insn a, b;
        memset(&a, 0, sizeof a);
        memset(&b, 0, sizeof b);
        int ra = ocerz_decode(code, sizeof code, 0x140001000ull, &a);
        int rb = ocerz_decode_mode(code, sizeof code, 0x140001000ull, &b, 0);
        if (ra != rb || memcmp(&a, &b, sizeof a) != 0) {
            printf("FAIL default entry: %02x %02x diverges from mode32=0\n",
                   code[0], code[1]);
            if (++fails > 4)
                break;
        } else if (ra == OCERZ_OK && a.mode32 != 0) {
            printf("FAIL default entry: %02x %02x reports mode32=%u\n",
                   code[0], code[1], a.mode32);
            if (++fails > 4)
                break;
        }
    }
    return fails;
}

int main(void)
{
    int n = (int)(sizeof cases / sizeof cases[0]);
    int fails = 0;
    for (int i = 0; i < n; i++)
        fails += run_case(&cases[i]);
    int nbad = (int)(sizeof bad_cases / sizeof bad_cases[0]);
    for (int i = 0; i < nbad; i++)
        fails += run_bad(&bad_cases[i]);
    fails += check_rex_still_rex();
    fails += check_82_aliases_80();
    fails += check_default_entry();
    if (fails == 0) {
        printf("test_decode32: all %d cases + %d undecodable + alias/REX sweeps passed\n",
               n, nbad);
        return 0;
    }
    printf("test_decode32: %d failures across %d cases\n", fails, n);
    return 1;
}
